# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['group', 'name'], 'verbose_name': '🎪 Venue'},
        ),
        migrations.AlterModelOptions(
            name='venuegroup',
            options={'ordering': ['short_name'], 'verbose_name': '🏢 Venue Group'},
        ),
    ]
