# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20160109_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuegroup',
            name='team_capacity',
            field=models.IntegerField(blank=True, help_text='The greatest possible number of teams that can debate in this venue group', null=True),
        ),
    ]
