# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20160201_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AlterModelOptions(
            name='venuegroup',
            options={'ordering': ['short_name']},
        ),
    ]
