# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20160402_1609'),
        ('participants', '0013_auto_20160507_1521'),
        ('venues', '0006_auto_20160507_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicatorVenueConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionVenueConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Division')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionVenueConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamVenueConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
