# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actionlog', '0001_initial'),
        ('adjfeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogentry',
            name='adjudicator_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback'),
        ),
        migrations.AddField(
            model_name='actionlogentry',
            name='adjudicator_test_score_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorTestScoreHistory'),
        ),
    ]
