# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('results', '0001_initial'),
        ('motions', '0001_initial'),
        ('breakqual', '0001_initial'),
        ('actionlog', '0002_auto_20160103_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogentry',
            name='ballot_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='results.BallotSubmission'),
        ),
        migrations.AddField(
            model_name='actionlogentry',
            name='break_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breakqual.BreakCategory'),
        ),
        migrations.AddField(
            model_name='actionlogentry',
            name='debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draw.Debate'),
        ),
        migrations.AddField(
            model_name='actionlogentry',
            name='motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motions.Motion'),
        ),
    ]
