# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0004_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlogentry',
            options={'verbose_name': '🕐 Action Log Entry', 'verbose_name_plural': '🕐 Action Log Entries'},
        ),
    ]
