# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_auto_20160507_1521'),
        ('actionlog', '0006_auto_20160228_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogentry',
            name='adjudicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.CharField(choices=[('ba.disc', 'Discarded ballot set'), ('ba.ckin', 'Checked in ballot set'), ('ba.crea', 'Created ballot set'), ('ba.edit', 'Edited ballot set'), ('ba.conf', 'Confirmed ballot set'), ('ba.subm', 'Submitted ballot set from the public form'), ('fb.subm', 'Submitted feedback from the public form'), ('fb.save', 'Saved feedback'), ('ts.edit', 'Edited adjudicator test score'), ('aj.note', 'Set adjudicator note'), ('aa.save', 'Saved adjudicator allocation'), ('ve.save', 'Saved venues'), ('dr.crea', 'Created draw'), ('dr.conf', 'Confirmed draw'), ('dr.rele', 'Released draw'), ('dr.unre', 'Unreleased draw'), ('dr.unre', 'Saved divisions'), ('mo.edit', 'Added/edited motion'), ('mo.rele', 'Released motions'), ('mo.unre', 'Unreleased motions'), ('db.im.edit', 'Edited debate importance'), ('br.aj.set', 'Changed adjudicator breaking status'), ('br.el.edit', 'Edited break eligibility'), ('br.gene', 'Generated the teams break for all categories'), ('br.upda', 'Updated the teams break for all categories'), ('br.upd1', 'Updated the teams break'), ('br.rm.edit', 'Edited breaking team remarks'), ('rd.st.set', 'Set start time'), ('av.tm.save', 'Edited teams availability'), ('av.aj.save', 'Edited adjudicators availability'), ('av.ve.save', 'Edited venue availability'), ('op.edit', 'Edited tournament options')], max_length=10),
        ),
    ]
