# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('availability', '0002_checkin_person'),
        ('venues', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round'),
        ),
        migrations.AddField(
            model_name='activevenue',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round'),
        ),
        migrations.AddField(
            model_name='activevenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue'),
        ),
        migrations.AddField(
            model_name='activeteam',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round'),
        ),
        migrations.AddField(
            model_name='activeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team'),
        ),
        migrations.AddField(
            model_name='activeadjudicator',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='activeadjudicator',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='activevenue',
            unique_together=set([('venue', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='activeteam',
            unique_together=set([('team', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='activeadjudicator',
            unique_together=set([('adjudicator', 'round')]),
        ),
    ]
