# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tournaments', '0013_remove_tournament_release_all'),
        ('availability', '0003_auto_20160103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='roundavailability',
            unique_together=set([('round', 'content_type', 'object_id')]),
        ),
    ]
