# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_delete_old_availability_models'),
        ('availability', '0005_convert_availability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activeadjudicator',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='activeadjudicator',
            name='adjudicator',
        ),
        migrations.RemoveField(
            model_name='activeadjudicator',
            name='round',
        ),
        migrations.AlterUniqueTogether(
            name='activeteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='activeteam',
            name='round',
        ),
        migrations.RemoveField(
            model_name='activeteam',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='activevenue',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='activevenue',
            name='round',
        ),
        migrations.RemoveField(
            model_name='activevenue',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='person',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='round',
        ),
        migrations.AlterModelOptions(
            name='roundavailability',
            options={'verbose_name_plural': 'round availabilities'},
        ),
        migrations.DeleteModel(
            name='ActiveAdjudicator',
        ),
        migrations.DeleteModel(
            name='ActiveTeam',
        ),
        migrations.DeleteModel(
            name='ActiveVenue',
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
