# Generated by Django 2.0.2 on 2018-03-01 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='checkin')),
            ],
            options={
                'verbose_name': 'check-in event',
                'verbose_name_plural': 'check-in events',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{6,}$', 'Only up 6 alphanumeric characters are allowed.')])),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('content_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'draw'), ('model', 'debate'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'participants'), ('model', 'person'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'venues'), ('model', 'venue'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),  # noqa: E501
            ],
            options={
                'verbose_name': 'check-in identifier',
                'verbose_name_plural': 'check-in identifiers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkins.Identifier', verbose_name='identifier'),
        ),
    ]
