# Generated by Django 2.0.2 on 2018-03-16 06:52

import checkins.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('checkins', '0001_initial'), ('checkins', '0002_auto_20180302_1125'), ('checkins', '0003_auto_20180302_1232'), ('checkins', '0004_auto_20180304_2218'), ('checkins', '0005_event_tournament'), ('checkins', '0006_auto_20180316_1722'), ('checkins', '0007_auto_20180316_1750')]

    dependencies = [
        ('venues', '0002_auto_20180218_1311'),
        ('draw', '0002_auto_20171110_0905'),
        ('participants', '0002_auto_20171201_1130'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tournaments', '0002_remove_tournament_welcome_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='checkin')),
            ],
            options={
                'verbose_name': 'check-in event',
                'verbose_name_plural': 'check-in events',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{6,}$', 'Only up 6 alphanumeric characters are allowed.')])),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('content_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'draw'), ('model', 'debate'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'participants'), ('model', 'person'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'venues'), ('model', 'venue'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'check-in identifier',
                'verbose_name_plural': 'check-in identifiers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkins.Identifier', verbose_name='identifier'),
        ),
        migrations.CreateModel(
            name='DebateIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('debate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='draw.Debate', verbose_name='debate')),
            ],
            options={
                'verbose_name_plural': 'debate identifiers',
                'verbose_name': 'debate identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='participants.Person', verbose_name='person')),
            ],
            options={
                'verbose_name_plural': 'person identifiers',
                'verbose_name': 'person identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.CreateModel(
            name='VenueIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='venues.Venue', verbose_name='venue')),
            ],
            options={
                'verbose_name_plural': 'venue identifiers',
                'verbose_name': 'venue identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={},
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='check-in time'),
        ),
        migrations.RenameField(
            model_name='Identifier',
            old_name='identifier',
            new_name='barcode',
        ),
        migrations.AlterField(
            model_name='identifier',
            name='barcode',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{6}$', message='The identifier must be exactly 6 alphanumeric characters.')], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='barcode',
            field=models.CharField(default=checkins.models.generate_identifier, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='The identifier must be exactly 6 alphanumeric characters.')], verbose_name='identifier'),
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identifier',
            name='barcode',
            field=models.CharField(default=checkins.models.generate_identifier, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='The barcode must be exactly 6 alphanumeric characters.')], verbose_name='barcode'),
        ),
    ]
