# Generated by Django 2.0.4 on 2018-04-20 10:44

import checkins.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial_squashed_0007_auto_20180316_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='barcode',
            field=models.CharField(default=checkins.models.generate_identifier, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4,20}$', message='The barcode must contain between 4 and 20 digits.')], verbose_name='barcode'),
        ),
    ]
