# Generated by Django 2.0.2 on 2018-03-02 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20171110_0905'),
        ('participants', '0002_auto_20171201_1130'),
        ('venues', '0002_auto_20180218_1311'),
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('debate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='draw.Debate', verbose_name='debate')),
            ],
            options={
                'verbose_name_plural': 'debate identifiers',
                'verbose_name': 'debate identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participants.Person', verbose_name='person')),
            ],
            options={
                'verbose_name_plural': 'person identifiers',
                'verbose_name': 'person identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.CreateModel(
            name='VenueIdentifier',
            fields=[
                ('identifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkins.Identifier')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue', verbose_name='venue')),
            ],
            options={
                'verbose_name_plural': 'venue identifiers',
                'verbose_name': 'venue identifier',
            },
            bases=('checkins.identifier',),
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={},
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='check-in time'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{6}$', message='The identifier must be exactly 6 alphanumeric characters.')], verbose_name='identifier'),
        ),
    ]
