# Generated by Django 2.0.2 on 2018-03-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_auto_20180302_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateidentifier',
            name='debate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='draw.Debate', verbose_name='debate'),
        ),
        migrations.AlterField(
            model_name='personidentifier',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='participants.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='venueidentifier',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_identifier', to='venues.Venue', verbose_name='venue'),
        ),
    ]
