# Generated by Django 2.2.9 on 2020-06-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_auto_20181224_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueidentifier',
            options={'verbose_name': 'room identifier', 'verbose_name_plural': 'room identifiers'},
        ),
    ]
