# Generated by Django 2.0.2 on 2018-03-04 11:18

import checkins.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_auto_20180302_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='identifier',
            field=models.CharField(default=checkins.models.generate_identifier, max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='The identifier must be exactly 6 alphanumeric characters.')], verbose_name='identifier'),
        ),
    ]
