# Generated by Django 2.0.2 on 2018-03-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_welcome_msg'),
        ('checkins', '0004_auto_20180304_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='tournament'),
            preserve_default=False,
        ),
    ]
