# Generated by Django 2.0.2 on 2018-03-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_event_tournament'),
    ]

    operations = [
        migrations.RenameField('Identifier', 'identifier', 'barcode'),
    ]
