# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateUrlSentMailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_type', models.CharField(choices=[('b', 'ballot'), ('f', 'feedback')], max_length=1, verbose_name='URL type')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail address')),
                ('url_key', models.SlugField(max_length=24, verbose_name='URL key')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('adjudicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator', verbose_name='recipient adjudicator')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Speaker', verbose_name='recipient speaker')),
            ],
            options={
                'verbose_name': 'private URL sent mail record',
                'verbose_name_plural': 'private URL sent mail records',
            },
        ),
    ]
