# Generated by Django 2.0.5 on 2018-07-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privateurls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateurlsentmailrecord',
            name='adjudicator',
        ),
        migrations.RemoveField(
            model_name='privateurlsentmailrecord',
            name='speaker',
        ),
        migrations.DeleteModel(
            name='PrivateUrlSentMailRecord',
        ),
    ]
