# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tournaments.Tournament', verbose_name='instance')),
            ],
            options={
                'verbose_name': 'tournament preference',
                'verbose_name_plural': 'tournament preferences',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournamentpreferencemodel',
            unique_together=set([('instance', 'section', 'name')]),
        ),
    ]
