# Generated by Django 2.0.2 on 2018-02-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO options_tournamentpreferencemodel (section, name, raw_value, instance_id) SELECT 'public_features', 'welcome_message', welcome_msg, id FROM tournaments_tournament ON CONFLICT (instance_id, section, name) DO UPDATE SET raw_value=EXCLUDED.raw_value;",
            "UPDATE tournaments_tournament t SET welcome_msg=o.raw_value FROM options_tournamentpreferencemodel o WHERE o.instance_id=t.id AND o.section='public_features' AND o.name='welcome_message';",
            elidable=True,
        ),
    ]
