# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0003_auto_20160109_1834'),
        ('options', '0003_auto_20160111_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tournaments.Tournament')),
            ],
            options={
                'verbose_name': 'Tournament Preference',
                'abstract': False,
                'verbose_name_plural': 'Tournament Preferencess',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournamentpreferencemodel',
            unique_together=set([('instance', 'section', 'name')]),
        ),
    ]
