# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_auto_20160120_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentpreferencemodel',
            options={'verbose_name': 'tournament preference'},
        ),
    ]
