# Generated by Django 2.1.3 on 2018-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0006_convert_public_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentpreferencemodel',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tournamentpreferencemodel',
            name='raw_value',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Value'),
        ),
    ]
