# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0009_participant_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentpreferencemodel',
            options={'verbose_name': 'tournament preference', 'verbose_name_plural': 'tournament preferences'},
        ),
        migrations.AlterField(
            model_name='tournamentpreferencemodel',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tournaments.Tournament', verbose_name='instance'),
        ),
    ]
