# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicatorAdjudicatorConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'adjudicator-adjudicator conflict',
                'verbose_name_plural': 'adjudicator-adjudicator conflicts',
            },
        ),
        migrations.CreateModel(
            name='AdjudicatorConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'adjudicator-team conflict',
                'verbose_name_plural': 'adjudicator-team conflicts',
            },
        ),
        migrations.CreateModel(
            name='AdjudicatorInstitutionConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'adjudicator-institution conflict',
                'verbose_name_plural': 'adjudicator-institution conflicts',
            },
        ),
        migrations.CreateModel(
            name='DebateAdjudicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'chair'), ('P', 'panellist'), ('T', 'trainee')], max_length=2, verbose_name='type')),
                ('timing_confirmed', models.NullBooleanField(verbose_name='available?')),
            ],
            options={
                'verbose_name': 'debate adjudicator',
                'verbose_name_plural': 'debate adjudicators',
            },
        ),
    ]
