# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0002_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicatoradjudicatorconflict',
            options={'verbose_name': '💜 Adj Adj Conflict'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatorconflict',
            options={'verbose_name': '❤️ Adj Team Conflict'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatorinstitutionconflict',
            options={'verbose_name': '💛 Adj Institution Conflict'},
        ),
        migrations.AlterModelOptions(
            name='debateadjudicator',
            options={'verbose_name': '🙉 Debate Adjudicator'},
        ),
    ]
