# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('draw', '0001_initial'),
        ('adjallocation', '0002_debateadjudicator_adjudicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateadjudicator',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.Debate', verbose_name='debate'),
        ),
        migrations.AddField(
            model_name='adjudicatorinstitutionconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator', verbose_name='adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorinstitutionconflict',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator', verbose_name='adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='adjudicatoradjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicatoradjudicatorconflict_source_set', to='participants.Adjudicator', verbose_name='adjudicator 1'),
        ),
        migrations.AddField(
            model_name='adjudicatoradjudicatorconflict',
            name='conflict_adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicatoradjudicatorconflict_target_set', to='participants.Adjudicator', verbose_name='adjudicator 2'),
        ),
        migrations.AlterUniqueTogether(
            name='debateadjudicator',
            unique_together=set([('debate', 'adjudicator')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorinstitutionconflict',
            unique_together=set([('adjudicator', 'institution')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorconflict',
            unique_together=set([('adjudicator', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatoradjudicatorconflict',
            unique_together=set([('adjudicator', 'conflict_adjudicator')]),
        ),
    ]
