# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0003_auto_20160109_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateadjudicator',
            name='timing_confirmed',
            field=models.NullBooleanField(),
        ),
    ]
