# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0004_debateadjudicator_timing_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateadjudicator',
            name='timing_confirmed',
            field=models.NullBooleanField(verbose_name='Available? '),
        ),
    ]
