# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0006_auto_20160228_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debateadjudicator',
            unique_together=set([('debate', 'adjudicator')]),
        ),
    ]
