# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0007_auto_20160521_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatoradjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicatoradjudicatorconflict_source_set', to='participants.Adjudicator'),
        ),
        migrations.AlterField(
            model_name='adjudicatoradjudicatorconflict',
            name='conflict_adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjudicatoradjudicatorconflict_target_set', to='participants.Adjudicator', verbose_name='Adjudicator'),
        ),
    ]
