# Generated by Django 3.1.1 on 2020-09-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0008_auto_20181019_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateadjudicator',
            name='timing_confirmed',
            field=models.BooleanField(null=True, verbose_name='available?'),
        ),
    ]
