# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0039_auto_20170923_1118'),
        ('adjallocation', '0009_auto_20170918_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adjudicatoradjudicatorconflict',
            unique_together=set([('adjudicator', 'conflict_adjudicator')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorconflict',
            unique_together=set([('adjudicator', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorinstitutionconflict',
            unique_together=set([('adjudicator', 'institution')]),
        ),
    ]
