# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0004_auto_20160228_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motion',
            options={'ordering': ('seq',)},
        ),
    ]
