# Generated by Django 2.0.5 on 2018-07-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0004_auto_20180420_2040'),
        ('tournaments', '0002_remove_tournament_welcome_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('p', 'team points'), ('c', 'ballot confirmed'), ('f', 'feedback URL'), ('b', 'ballot URL')], max_length=1, verbose_name='event')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('method', models.CharField(choices=[('e', 'email')], max_length=1, verbose_name='method')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Person', verbose_name='recepient')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round', verbose_name='round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'message sent record',
                'verbose_name_plural': 'message sent records',
                'ordering': ['timestamp'],
            },
        ),
    ]
