# Generated by Django 2.0.6 on 2018-07-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20180420_2040'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesentrecord',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
