# Generated by Django 2.0.8 on 2018-10-23 19:44
# Extended manually to create BulkNotification objects and Message-IDs
import email
import itertools
import re

from django.db import migrations


def create_bulk_notifications(apps, schema_editor):
    SentMessageRecord = apps.get_model("notifications", "SentMessageRecord")
    BulkNotification = apps.get_model("notifications", "BulkNotification")

    current_bulk = None
    for key, group in itertools.groupby(SentMessageRecord.objects.all(), lambda x: (x.event, x.round, x.tournament)):
        messages = list(group)

        current_bulk = BulkNotification.objects.create(event=key[0], timestamp=messages[0].timestamp,
                                                       round=key[1], tournament=key[2]).id
        for m in messages:
            m.notification_id = current_bulk
            m.save()


def get_message_ids(apps, schema_editor):
    SentMessageRecord = apps.get_model("notifications", "SentMessageRecord")

    for m in SentMessageRecord.objects.all():
        message = email.message_from_string(m.message)

        m.message_id = message.get('Message-ID')
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_separate_tables'),
    ]

    operations = [
        migrations.RunPython(create_bulk_notifications),
        migrations.RunPython(get_message_ids),
    ]
