# Generated by Django 3.1.1 on 2020-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20200902_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='body_template',
            field=models.TextField(null=True, verbose_name='body template'),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='subject_template',
            field=models.TextField(null=True, verbose_name='subject template'),
        ),
        migrations.AlterField(
            model_name='bulknotification',
            name='event',
            field=models.CharField(blank=True, choices=[('p', 'team points'), ('c', 'ballot confirmed'), ('f', 'feedback URL'), ('b', 'ballot URL'), ('u', 'landing page URL'), ('d', 'adjudicator draw released'), ('t', 'team registration'), ('a', 'adjudicator registration'), ('m', 'motion(s) released'), ('r', 'team draw released'), ('', 'custom message')], max_length=1, verbose_name='event'),
        ),
    ]
