# Generated by Django 5.0.4 on 2024-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20201018_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='event',
            field=models.CharField(choices=[('p', 'team points'), ('c', 'ballot confirmed'), ('f', 'feedback URL'), ('b', 'ballot URL'), ('u', 'landing page URL'), ('d', 'adjudicator draw released'), ('t', 'team registration'), ('a', 'adjudicator registration'), ('m', 'motion(s) released'), ('r', 'team draw released'), ('', 'custom message')], max_length=20, verbose_name='event'),
        ),
    ]
