# Generated by Django 5.2.7 on 2025-10-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_bulknotification_event'),
        ('participants', '0029_alter_person_last_name'),
        ('push_notifications', '0011_alter_apnsdevice_registration_id'),
        ('tournaments', '0013_scheduleevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstatus',
            name='event',
            field=models.CharField(choices=[('processed', 'Processed'), ('dropped', 'Dropped'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('bounce', 'Bounced'), ('open', 'Opened'), ('click', 'Clicked'), ('unsubscribe', 'Unsubscribed'), ('spamreport', 'Marked as spam'), ('group_unsubscribe', 'Unsubscribed from group'), ('group_resubscribe', 'Resubscribed to group'), ('failed', 'Failed to send')], max_length=20, verbose_name='event'),
        ),
        migrations.CreateModel(
            name='ParticipantWebPushDevice',
            fields=[
                ('webpushdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.webpushdevice')),
                ('language', models.CharField(blank=True, default='', help_text='The language preference of the participant at subscription time', max_length=10, verbose_name='language')),
                ('participant', models.ForeignKey(help_text='The participant (adjudicator or speaker) who owns this device', on_delete=django.db.models.deletion.CASCADE, to='participants.person', verbose_name='participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'WebPush device',
                'verbose_name_plural': 'WebPush devices',
            },
            bases=('push_notifications.webpushdevice',),
        ),
    ]
