# Generated by Django 5.2.12 on 2026-06-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_emailstatus_event_participantwebpushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='event',
            field=models.CharField(choices=[('p', 'team points'), ('c', 'ballot confirmed'), ('f', 'feedback URL'), ('b', 'ballot URL'), ('u', 'landing page URL'), ('d', 'adjudicator draw released'), ('t', 'team registration'), ('a', 'adjudicator registration'), ('m', 'motion(s) released'), ('r', 'team draw released'), ('i', 'institution registration'), ('s', 'participant slots allocated'), ('v', 'user invitation'), ('ic', 'custom institution message'), ('', 'custom message')], max_length=20, verbose_name='event'),
        ),
    ]
