# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20160128_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='draw_status',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Draft'), ('C', 'Confirmed'), ('R', 'Released')], default='N', help_text="The status of this round's draw", max_length=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='feedback_weight',
            field=models.FloatField(default=0, help_text="The extent to which each adjudicator's overall score depends on feedback vs their test score. At 0, it is 100% drawn from their test score, at 1 it is 100% drawn from feedback."),
        ),
        migrations.AlterField(
            model_name='round',
            name='motions_released',
            field=models.BooleanField(default=False, help_text='Whether motions will appear on the public website, assuming that feature is turned on'),
        ),
        migrations.AlterField(
            model_name='round',
            name='silent',
            field=models.BooleanField(default=False, help_text="If marked silent, information about this round (such as it's results) will not be shown publicly."),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(help_text='The full name used on the homepage, e.g. "Australasian Intervarsity Debating Championships 2016"', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='release_all',
            field=models.BooleanField(default=False, help_text='This releases all results, including silent rounds; do so only after the tournament is finished!'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='seq',
            field=models.IntegerField(blank=True, help_text='A number that determines the relative order in which tournaments are displayed on the homepage.', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='The name used in the menu, e.g. "Australs 2016"', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(help_text='The sub-URL of the tournament, cannot have spaces, e.g. "australs2016"', unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='welcome_msg',
            field=models.TextField(blank=True, default='', help_text='Text/html entered here shows on the homepage for this tournament', null=True),
        ),
    ]
