# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateTeamMotionPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(help_text='The order in which motions are displayed')),
                ('text', models.CharField(help_text='The motion itself, e.g., "This House would straighten all bananas"', max_length=500)),
                ('reference', models.CharField(help_text='Shortcode for the motion, e.g., "Bananas"', max_length=100)),
                ('flagged', models.BooleanField(default=False, help_text='For WADL: Allows for particular motions to be flagged as contentious')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
