# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motions', '0001_initial'),
        ('draw', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateteammotionpreference',
            name='ballot_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.BallotSubmission', verbose_name='ballot submission'),
        ),
        migrations.AddField(
            model_name='debateteammotionpreference',
            name='debate_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.DebateTeam', verbose_name='debate team'),
        ),
        migrations.AddField(
            model_name='debateteammotionpreference',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motions.Motion', verbose_name='motion'),
        ),
        migrations.AlterUniqueTogether(
            name='debateteammotionpreference',
            unique_together=set([('debate_team', 'preference', 'ballot_submission')]),
        ),
    ]
