# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0002_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debateteammotionpreference',
            options={'verbose_name': '💌 Motion Preference'},
        ),
        migrations.AlterModelOptions(
            name='motion',
            options={'ordering': ['seq'], 'verbose_name': '📨 Motion'},
        ),
    ]
