# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0003_auto_20160109_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debateteammotionpreference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='motion',
            options={'ordering': ['seq']},
        ),
    ]
