# Generated by Django 2.1.8 on 2019-07-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0003_auto_20180402_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='motion',
            name='flagged',
        ),
    ]
