# Generated by Django 3.1.1 on 2020-09-19 10:31

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0004_remove_league_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='info_slide',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', help_text='The information slide for this topic; if it has one', verbose_name='info slide'),
        ),
    ]
