# Generated by Django 5.0.4 on 2024-05-04 13:21

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_alter_teamsideallocation_unique_together_and_more'),
        ('motions', '0005_motions_mtm'),
        ('results', '0015_alter_ballotsubmission_submitter_type'),
        ('tournaments', '0012_alter_round_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debateteammotionpreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roundmotion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='debateteammotionpreference',
            constraint=utils.models.UniqueConstraint(fields=('debate_team', 'preference', 'ballot_submission'), name='motions_debateteammotionpreference_debate_team__preference__ballot_submission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='roundmotion',
            constraint=utils.models.UniqueConstraint(fields=('round', 'seq'), name='motions_roundmotion_round__seq_uniq'),
        ),
    ]
