# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0005_auto_20160507_1521'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='divisions.Division'),
        ),
    ]
