# Generated by Django 3.1.1 on 2020-11-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20200620_1326'),
        ('motions', '0005_round_motions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoundMotions',
            new_name='RoundMotion',
        ),
    ]
