# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0008_auto_20171005_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='info_slide',
            field=models.TextField(default='', help_text='The information slide for this topic; if it has one', verbose_name='info slide'),
        ),
    ]
