# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0009_motion_info_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='info_slide',
            field=models.TextField(blank=True, default='', help_text='The information slide for this topic; if it has one', verbose_name='info slide'),
        ),
    ]
