# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_auto_20170228_0941'),
        ('divisions', '0002_auto_20170121_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='venue_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.VenueCategory'),
        ),
    ]
