# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0004_convert_venuegroup_to_venuecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='venue_group',
        ),
    ]
