# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakqual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The institution\'s full name, e.g., "University of Cambridge", "Victoria University of Wellington"', max_length=100)),
                ('code', models.CharField(help_text='What the institution is typically called for short, e.g., "Cambridge", "Vic Wellington"', max_length=20)),
                ('abbreviation', models.CharField(default='', help_text='For extremely confined spaces, e.g., "Camb", "VicWgtn"', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('barcode_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('novice', models.BooleanField(default=False)),
                ('checkin_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('pronoun', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Do not include institution name (see "uses institutional prefix" below)', max_length=150, verbose_name='Full name or suffix')),
                ('short_reference', models.CharField(help_text='The name shown in the draw. Do not include institution name (see "uses institutional prefix" below)', max_length=35, verbose_name='Short name/suffix')),
                ('emoji_seq', models.IntegerField(blank=True, help_text='Emoji number to use for this team', null=True)),
                ('use_institution_prefix', models.BooleanField(default=False, help_text='If ticked, a team called "1" from Victoria will be shown as "Victoria 1" ', verbose_name='Uses institutional prefix')),
                ('url_key', models.SlugField(blank=True, max_length=24, null=True, unique=True)),
                ('type', models.CharField(choices=[('N', 'None'), ('S', 'Swing'), ('C', 'Composite'), ('B', 'Bye')], default='N', max_length=1)),
                ('break_categories', models.ManyToManyField(blank=True, to='breakqual.BreakCategory')),
            ],
            options={
                'ordering': ['tournament', 'institution', 'short_reference'],
            },
        ),
        migrations.CreateModel(
            name='Adjudicator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.Person')),
                ('test_score', models.FloatField(default=0)),
                ('url_key', models.SlugField(blank=True, max_length=24, null=True, unique=True)),
                ('breaking', models.BooleanField(default=False)),
                ('independent', models.BooleanField(default=False)),
                ('adj_core', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tournament', 'institution', 'name'],
            },
            bases=('participants.person',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.Person')),
            ],
            bases=('participants.person',),
        ),
    ]
