# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicator',
            options={'ordering': ['tournament', 'institution', 'name'], 'verbose_name': '👂 Adjudicator'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': '🏫 Institution'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '🌏 Region'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': '🔊 Speaker'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['tournament', 'institution', 'short_reference'], 'verbose_name': '👯 Team'},
        ),
    ]
