# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_auto_20160202_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicator',
            options={'ordering': ['tournament', 'institution', 'name']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['tournament', 'institution', 'short_reference']},
        ),
    ]
