# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.Venue', verbose_name='venue'),
        ),
        migrations.AlterUniqueTogether(
            name='teamsideallocation',
            unique_together=set([('round', 'team')]),
        ),
    ]
