# Generated by Django 2.0.2 on 2018-03-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20171110_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='ballot_in',
        ),
    ]
