# Generated by Django 2.1.8 on 2019-07-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_remove_debate_ballot_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='division',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='time',
        ),
    ]
