# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20160109_1834'),
        ('participants', '0003_auto_20160109_1834'),
        ('draw', '0003_auto_20160103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionVenuePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
            options={
                'ordering': ['priority'],
                'verbose_name': '🏩 Institutional Venue Preference',
            },
        ),
        migrations.AlterModelOptions(
            name='debate',
            options={'verbose_name': '⚖ Debate'},
        ),
        migrations.AlterModelOptions(
            name='debateteam',
            options={'verbose_name': '🙊 Debate Team'},
        ),
        migrations.AlterModelOptions(
            name='teamvenuepreference',
            options={'ordering': ['priority'], 'verbose_name': '🏩 Team Venue Preference'},
        ),
    ]
