# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_auto_20160109_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionvenuepreference',
            options={'ordering': ['priority'], 'verbose_name': '🏩 Institutional Venue Pref'},
        ),
        migrations.AlterModelOptions(
            name='teamvenuepreference',
            options={'ordering': ['priority'], 'verbose_name': '🏩 Team Venue Pref'},
        ),
    ]
