# Generated by Django 3.1.1 on 2020-09-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_auto_20200613_0952'),
        ('draw', '0005_auto_20200705_1525'),
    ]

    operations = [
    ]
