# Generated by Django 4.1.7 on 2023-09-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw", "0007_auto_20201003_0205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debateteam",
            name="side",
            field=models.CharField(
                choices=[
                    ("aff", "affirmative"),
                    ("neg", "negative"),
                    ("og", "opening government"),
                    ("oo", "opening opposition"),
                    ("cg", "closing government"),
                    ("co", "closing opposition"),
                    ("bye", "bye"),
                ],
                max_length=3,
                verbose_name="side",
            ),
        ),
        migrations.AlterField(
            model_name="teamsideallocation",
            name="side",
            field=models.CharField(
                choices=[
                    ("aff", "affirmative"),
                    ("neg", "negative"),
                    ("og", "opening government"),
                    ("oo", "opening opposition"),
                    ("cg", "closing government"),
                    ("co", "closing opposition"),
                    ("bye", "bye"),
                ],
                max_length=3,
                verbose_name="side",
            ),
        ),
    ]
