# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_debate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionvenuepreference',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionvenuepreference',
            name='venue_group',
        ),
        migrations.RemoveField(
            model_name='teamvenuepreference',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamvenuepreference',
            name='venue_group',
        ),
        migrations.DeleteModel(
            name='InstitutionVenuePreference',
        ),
        migrations.DeleteModel(
            name='TeamVenuePreference',
        ),
    ]
