# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_delete_teamvenuepreference_institutionvenuepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divisions.Division'),
        ),
    ]
