# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_auto_20160621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
