# Generated by Django 4.1.7 on 2023-12-10 03:18
from itertools import chain

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("draw", "0009_alter_teamsideallocation_unique_together_and_more"),
    ]

    operations = list(chain(*[
        [
            migrations.AddField(
                model_name=table,
                name="side_",
                field=models.IntegerField(verbose_name="side sequence", null=True),
            ),
            migrations.RunSQL(
                "UPDATE draw_%s SET side_=CASE WHEN side IN ('aff', 'og') THEN 0 WHEN side IN ('neg', 'oo') THEN 1 WHEN side = 'cg' THEN 2 WHEN side = 'co' THEN 3 ELSE -1 END;" % table,
                migrations.RunSQL.noop
            ),
            migrations.AlterField(
                model_name=table,
                name='side_',
                field=models.IntegerField(verbose_name="side sequence"),
            ),
            migrations.RemoveField(
                model_name=table,
                name='side',
            ),
            migrations.RenameField(
                model_name=table,
                old_name='side_',
                new_name='side',
            ),
    ] for table in ['debateteam', 'teamsideallocation']]))
