# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draw", "0010_alter_debateteam_side_alter_teamsideallocation_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="debate",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional start time for this debate, if it differs from the round schedule.",
                null=True,
                verbose_name="scheduled time",
            ),
        ),
    ]
