# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_auto_20160630_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='flags',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
