# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_auto_20160914_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateteam',
            name='position',
            field=models.CharField(choices=[('A', 'affirmative'), ('N', 'negative'), ('u', 'unallocated')], max_length=1),
        ),
        migrations.AlterField(
            model_name='teampositionallocation',
            name='position',
            field=models.CharField(choices=[('A', 'affirmative'), ('N', 'negative'), ('u', 'unallocated')], max_length=1),
        ),
    ]
