# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_auto_20170120_2259'),
        ('draw', '0012_auto_20161119_1312'),
    ]

    operations = [
    ]
