# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0013_merge_20170120_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.Team'),
        ),
    ]
