# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0014_auto_20170304_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='importance',
            field=models.IntegerField(choices=[(-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
