# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0015_auto_20170606_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateteam',
            name='position',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('-', 'unallocated')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teampositionallocation',
            name='position',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('-', 'unallocated')], max_length=3),
        ),
    ]
