# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:53
from __future__ import unicode_literals

from django.db import migrations


def convert_debateteam_positions(apps, schema_editor):
    DebateTeam = apps.get_model("draw", "DebateTeam")
    DebateTeam.objects.filter(position='A').update(position='aff')
    DebateTeam.objects.filter(position='N').update(position='neg')
    DebateTeam.objects.filter(position='u').update(position='-')

    TeamPositionAllocation = apps.get_model("draw", "TeamPositionAllocation")
    TeamPositionAllocation.objects.filter(position='A').update(position='aff')
    TeamPositionAllocation.objects.filter(position='N').update(position='neg')
    TeamPositionAllocation.objects.filter(position='u').update(position='-')


def convert_debateteam_positions_reverse(apps, schema_editor):
    DebateTeam = apps.get_model("draw", "DebateTeam")
    DebateTeam.objects.filter(position='aff').update(position='A')
    DebateTeam.objects.filter(position='neg').update(position='N')
    DebateTeam.objects.filter(position='-').update(position='u')

    TeamPositionAllocation = apps.get_model("draw", "TeamPositionAllocation")
    TeamPositionAllocation.objects.filter(position='aff').update(position='A')
    TeamPositionAllocation.objects.filter(position='neg').update(position='N')
    TeamPositionAllocation.objects.filter(position='-').update(position='u')


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0016_auto_20170615_1953'),
    ]

    operations = [
        migrations.RunPython(convert_debateteam_positions, reverse_code=convert_debateteam_positions_reverse, elidable=True),
    ]
