# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0017_convert_debateteam_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPositionAllocation',
            new_name='TeamSideAllocation',
        ),
        migrations.RenameField(
            model_name='debateteam',
            old_name='position',
            new_name='side',
        ),
    ]
