# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0018_auto_20170615_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamsideallocation',
            old_name='position',
            new_name='side',
        ),
    ]
