# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0019_auto_20170615_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'verbose_name': 'debate', 'verbose_name_plural': 'debates'},
        ),
        migrations.AlterModelOptions(
            name='debateteam',
            options={'verbose_name': 'debate team', 'verbose_name_plural': 'debate teams'},
        ),
        migrations.AlterModelOptions(
            name='teamsideallocation',
            options={'verbose_name': 'team side allocation', 'verbose_name_plural': 'team side allocations'},
        ),
        migrations.AlterField(
            model_name='debate',
            name='ballot_in',
            field=models.BooleanField(default=False, verbose_name='ballot in'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='bracket',
            field=models.FloatField(default=0, verbose_name='bracket'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divisions.Division', verbose_name='division'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='importance',
            field=models.IntegerField(choices=[(-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2)], default=0, verbose_name='importance'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='result_status',
            field=models.CharField(choices=[('N', 'None'), ('P', 'Postponed'), ('D', 'Draft'), ('C', 'Confirmed')], default='N', max_length=1, verbose_name='result status'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='room_rank',
            field=models.IntegerField(default=0, verbose_name='room rank'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='time',
            field=models.DateTimeField(blank=True, help_text='The time/date of a debate if it is specifically scheduled', null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.Venue', verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='debateteam',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.Debate', verbose_name='debate'),
        ),
        migrations.AlterField(
            model_name='debateteam',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('-', 'unallocated')], max_length=3, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='debateteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round', verbose_name='round'),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('-', 'unallocated')], max_length=3, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team', verbose_name='team'),
        ),
    ]
