# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0020_auto_20170713_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateteam',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition'), ('-', 'unallocated')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition'), ('-', 'unallocated')], max_length=3),
        ),
    ]
