# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0020_auto_20170713_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='result_status',
            field=models.CharField(choices=[('N', 'none'), ('P', 'postponed'), ('D', 'draft'), ('C', 'confirmed')], default='N', max_length=1, verbose_name='result status'),
        ),
    ]
