# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0021_auto_20170813_1236'),
        ('draw', '0020_auto_20170618_1549'),
    ]

    operations = [
    ]
