# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0022_merge_20170813_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateteam',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition'), ('-', 'unallocated')], max_length=3, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition'), ('-', 'unallocated')], max_length=3, verbose_name='side'),
        ),
    ]
