# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0023_auto_20170813_1238'),
        ('draw', '0022_debateteam_flags'),
    ]

    operations = [
    ]
