# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0024_merge_20170813_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='sides_confirmed',
            field=models.BooleanField(default=True, help_text='If unchecked, the sides assigned to teams in this debate are just placeholders.', verbose_name='sides confirmed'),
        ),
        migrations.AlterField(
            model_name='debateteam',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition')], max_length=3, verbose_name='side'),
        ),
        migrations.AlterField(
            model_name='teamsideallocation',
            name='side',
            field=models.CharField(choices=[('aff', 'affirmative'), ('neg', 'negative'), ('og', 'opening government'), ('oo', 'opening opposition'), ('cg', 'closing government'), ('co', 'closing opposition')], max_length=3, verbose_name='side'),
        ),
    ]
