# -*- coding: utf-8 -*-
import random
import logging

logger = logging.getLogger(__name__)


def set_emoji(teams, tournament):
    """Sets the emoji of every team in `teams` to a randomly chosen and unique
    emoji.  Every team in `teams` must be from the same tournament, and that
    tournament must be provided as the second argument."""

    used_emoji = tournament.team_set.filter(emoji__isnull=False).values_list('emoji', flat=True)
    unused_emoji = [e for e in EMOJI_LIST if e[0] not in used_emoji]

    if len(teams) > len(unused_emoji):
        teams = teams[:len(unused_emoji)]
    emojis = random.sample(unused_emoji, len(teams))

    for team, emoji in zip(teams, emojis):
        team.emoji = emoji[0]
        if not team.code_name:
            team.code_name = emoji[1]
        team.save()


def pick_unused_emoji():
    """Picks an emoji that is not already in use by any team in the database. If
    no emoji are left, it returns `None`."""
    from .models import Team
    used_emoji = Team.objects.filter(emoji__isnull=False).values_list('emoji', flat=True)
    unused_emoji = [e[0] for e in EMOJI_LIST if e[0] not in used_emoji]

    try:
        return random.choice(unused_emoji)
    except IndexError:
        return None


def populate_code_names_from_emoji(teams, overwrite=True):
    """Populates team code names based on existing emoji."""
    count = 0

    for team in teams:
        try:
            new_code_name = EMOJI_NAMES[team.emoji]
        except KeyError:
            logger.warning("Unrecognized emoji for team %s: %s (%#x)", team.short_name, team.emoji, ord(team.emoji))
            continue

        if team.code_name:
            if team.code_name == new_code_name:
                continue
            elif overwrite:
                logger.info("Team %s already has code name %s, overwriting with %s",
                    team.short_name, team.code_name, new_code_name)
            else:
                logger.info("Team %s already has code name %s, leaving unchanged",
                    team.short_name, team.code_name)
                continue

        team.code_name = new_code_name
        team.save()
        count += 1

    return count


# With thanks to emojipedia.org
EMOJI_LIST = (
    # ---------------------
    # Unicode Version 1.1 (these all render using primitive icons)
    # ---------------------
    # NOSHOW    ("☺️", "White Smiling"),
    # NOSHOW    ("☹", "White Frowning"),
    # NOSHOW    ("☝️", "White Up Pointing Index"),
    # NOSHOW    ("✌️", "Victory Hand"),
    # NOSHOW    ("✍", "Writing Hand"),
    # NOSHOW    ("❤️", "Heavy Black Heart"),
    # NOSHOW    ("❣", "Heavy Heart Exclamation Mark Ornament"),
    # NOSHOW    ("☠", "Skull and Crossbones"),
    # NOSHOW    ("♨️", "Hot Springs"),
    # NOSHOW    ("✈️", "Airplane"),
    # NOSHOW    ("⌛", "Hourglass"),
    # NOSHOW    ("⌚", "Watch"),
    # DULL      ("♈", "Aries"),
    # DULL      ("♉", "Taurus"),
    # DULL      ("♊", "Gemini"),
    # DULL      ("♋", "Cancer"),
    # DULL      ("♌", "Leo"),
    # DULL      ("♍", "Virgo"),
    # DULL      ("♎", "Libra"),
    # DULL      ("♏", "Scorpius"),
    # DULL      ("♐", "Sagittarius"),
    # DULL      ("♑", "Capricorn"),
    # DULL      ("♒", "Aquarius"),
    # DULL      ("♓", "Pisces"),
    # NOSHOW    ("☀️", "Black Sun With Rays"),
                ("☁️", "Cloud"),
    # NOSHOW    ("☂", "Umbrella"),
                ("❄️", "Snowflake"),
    # NOSHOW    ("☃", "Snowman"),
    # NOSHOW    ("☄️", "☄️"),  #
                ("♠️", "Spade Suit"),
                ("♥️", "Heart Suit"),
                ("♦️", "Diamond Suit"),
                ("♣️", "Club Suit"),
    # DULL      ("▶️", "Black Right-Pointing Triangle"),
    # DULL      ("◀️", "Black Left-Pointing Triangle"),
    # NOSHOW    ("☎️", "Black Telephone"),
    # NOSHOW    ("⌨", "Keyboard"),
                ("✉️", "Envelope"),
    # NOSHOW    ("✏️", "Pencil"),
    # NOSHOW    ("✒️", "Black Nib"),
                ("✂️", "Scissors"),
    # DULL      ("↗️", "North East Arrow"),
    # DULL      ("➡️", "Black Rightwards Arrow"),
    # DULL      ("↘️", "South East Arrow"),
    # DULL      ("↙️", "South West Arrow"),
    # DULL      ("↖️", "North West Arrow"),
    # DULL      ("↕️", "Up Down Arrow"),
    # DULL      ("↔️", "Left Right Arrow"),
    # DULL      ("↩️", "Leftwards Arrow With Hook"),
    # DULL      ("↪️", "Rightwards Arrow With Hook"),
    # OFFENSIVE ("✡", "Star of David"),
    # OFFENSIVE ("☸", "Wheel of Dharma"),
    # OFFENSIVE ("☯", "Yin Yang"),
    # OFFENSIVE ("✝", "Latin Cross"),
    # OFFENSIVE ("☦", "Orthodox Cross"),
    # OFFENSIVE ("☪", "Star and Crescent"),
    # OFFENSIVE ("☮", "Peace Symbol"),
    # OFFENSIVE ("☢", "Radioactive Sign"),
    # OFFENSIVE ("☣", "Biohazard Sign"),
    # NOSHOW    ("☑️", "Ballot Box With Check"),
    # DULL      ("✔️", "Heavy Check Mark"),
    # DULL      ("✖️", "Heavy Multiplication X"),
    # DULL      ("✳️", "Eight Spoked Asterisk"),
    # DULL      ("✴️", "Eight Pointed Black Star"),
    # DULL      ("❇️", "Sparkle"),
    # NOSHOW    ("‼️", "Double Exclamation Mark"),
    # DULL      ("〰️", "Wavy Dash"),
    # DULL      ("©️", "Copyright Sign"),
    # DULL      ("®️", "Registered Sign"),
    # DULL      ("™️", "Trade Mark Sign"),
    # DULL      ("Ⓜ️", "Circled Latin Capital Letter M"),
    # DULL      ("㊗️", "Circled Ideograph Congratulation"),
    # DULL      ("㊙️", "Circled Ideograph Secret"),
    # DULL      ("▪️", "Black Square"),
    # DULL      ("▫️", "White Square"),
    # ---------------------
    # Unicode    Version 3.0
    # ---------------------
    # DULL      ("#⃣️", "Keycap Number Sign"),
    # DULL      ("*⃣", "Keycap Asterisk"),
    # DULL      ("0⃣️", "Keycap Digit Zero"),
    # DULL      ("1⃣️", "Keycap Digit One"),
    # DULL      ("2⃣️", "Keycap Digit Two"),
    # DULL      ("3⃣️", "Keycap Digit Three"),
    # DULL      ("4⃣️", "Keycap Digit Four"),
    # DULL      ("5⃣️", "Keycap Digit Five"),
    # DULL      ("6⃣️", "Keycap Digit Six"),
    # DULL      ("7⃣️", "Keycap Digit Seven"),
    # DULL      ("8⃣️", "Keycap Digit Eight"),
    # DULL      ("9⃣️", "Keycap Digit Nine"),
    # NOSHOW    ("⁉️", "Exclamation Question Mark"),
    # DULL      ("ℹ️", "Information Source"),
    # ---------------------
    # Unicode   Version 3.2
    # ---------------------
    # DULL      ("⤴️", "Arrow Pointing Rightwards Then Curving Upwards"),
    # DULL      ("⤵️", "Arrow Pointing Rightwards Then Curving Downwards"),
    # NOSHOW    ("♻️", "Black Universal Recycling Symbol"),
    # DULL      ("〽️", "Part Alternation Mark"),
    # DULL      ("◻️", "White Medium Square"),
    # DULL      ("◼️", "Black Medium Square"),
    # DULL      ("◽", "White Medium Small Square"),
    # DULL      ("◾", "Black Medium Small Square"),
    # ---------------------
    # Unicode    Version 4.0
    # ---------------------
                ("☕", "Hot Beverage"),
    # NOSHOW    ("⚠️", "Warning Sign"),
    # NOSHOW    ("☔", "Umbrella With Rain Drops"),
    # DULL      ("⏏", "Eject Symbol"),
    # DULL      ("⬆️", "Upwards Black Arrow"),
    # DULL      ("⬇️", "Downwards Black Arrow"),
    # DULL      ("⬅️", "Leftwards Black Arrow"),
    # NOSHOW    ("⚡", "High Voltage Sign"),
    # ---------------------
    # Unicode Version 4.1
    # ---------------------
    # NOSHOW    ("☘", "Shamrock"),
    # NOSHOW    ("⚓", "Anchor"),
    # NOSHOW    ("♿", "Wheelchair Symbol"),
    # NOSHOW    ("⚒", "Hammer and Pick"),
    # NOSHOW    ("⚙", "Gear"),
    # NOSHOW    ("⚗", "Alembic"),
    # UI USES   ("⚖", "Scales"),
    # NOSHOW    ("⚔", "Crossed Swords"),
    # NOSHOW    ("⚰", "Coffin"),
    # NOSHOW    ("⚱", "Funeral Urn"),
    # NOSHOW    ("⚜", "Fleur-De-Lis"),
    # NOSHOW    ("⚛", "Atom Symbol"),
    # DULL      ("⚪", "Medium White Circle"),
    # DULL      ("⚫", "Medium Black Circle"),
    # ---------------------
    # Unicode Version 5.1
    # ---------------------
    # DULL      ("🀄", "Mahjong Tile Red Dragon"),
    # NOSHOW    ("⭐", "White Medium Star"),
                ("⬛", "Black Square"),
                ("⬜", "White Square"),
    # ---------------------
    # Unicode Version 5.2
    # ---------------------
                ("⛑", "White Cross"),
                ("⛰", "Mountain"),
                ("⛪", "Church"),
    # DULL      ("⛲", "Fountain"),
                ("⛺", "Tent"),
    # DULL      ("⛽", "Fuel Pump"),
                ("⛵", "Sailboat"),
    # DULL      ("⛴", "Ferry"),
                ("⛔", "Stop"),
                ("⛅", "Overcast"),
                ("⛈", "Storm"),
                ("⛱", "Umbrella"),
                ("⛄", "Snowman"),
                ("⚽", "Soccer"),
    # NO SHOW   ("⚾", "Baseball"),
    # DULL      ("⛳", "Flag in Hole"),
                ("⛸", "Ice Skate"),
    # DULL      ("⛷", "Skier"),
    # DULL      ("⛹", "Person With Ball"),
                ("⛏", "Pick"),
    # OFFENSIVE ("⛓", "Chains"),
    # DULL      ("⛩", "Shinto Shrine"),
    # DULL      ("⭕", "Heavy Large Circle"),
    # DULL      ("❗", "Heavy Exclamation Mark Symbol"),
    # DULL      ("🅿️", "Negative Squared Latin Capital Letter P"),
    # DULL      ("🈯", "Squared CJK Unified Ideograph-6307"),
    # DULL      ("🈚", "Squared CJK Unified Ideograph-7121"),
    # ---------------------
    # Unicode Version 6.0
    # ---------------------
    # 2 SIMILAR ("😁", "Smiling Eyes"),
                ("😂", "Tears of Joy"),
    # 2 SIMILAR ("😃", "Smiling Face With Open Mouth"),
    # 2 SIMILAR ("😄", "Smiling Face With Open Mouth and Smiling Eyes"),
    # 2 SIMILAR ("😅", "Cold Sweat"),
                ("😆", "Closed Eyes"),
                ("😉", "Winky"),
                ("😊", "Smiling Eyes"),
    # 2 SIMILAR ("😋", "Face Savouring Delicious Food"),
                ("😎", "Sunglasses"),
                ("😍", "Heart Eyes"),
                ("😘", "Kissy"),
    # 2 SIMILAR ("😚", "Kissing Face With Closed Eyes"),
                ("😇", "Halo"),
                ("😐", "Neutral"),
    # 2 SIMILAR ("😶", "Face Without Mouth"),
                ("😏", "Smirking"),
                ("😣", "Persevering"),
                ("😥", "Disappointed"),
    # 2 SIMILAR ("😪", "Sleepy"),
    # 2 SIMILAR ("😫", "Tired"),
    # 2 SIMILAR ("😌", "Relieved"),
                ("😜", "Tongue Out"),
    # 2 SIMILAR ("😝", "Face With Stuck-Out Tongue and Tightly-Closed Eyes"),
    # 2 SIMILAR ("😒", "Unamused"),
                ("😓", "Cold Sweat"),
    # 2 SIMILAR ("😔", "Pensive"),
                ("😖", "Confounded"),
                ("😷", "Medical Mask"),
                ("😲", "Astonished"),
    # 2 SIMILAR ("😞", "Disappointed"),
    # 2 SIMILAR ("😤", "Face With Look of Triumph"),
    # 2 SIMILAR ("😢", "Crying"),
                ("😭", "Crying"),
    # 2 SIMILAR ("😨", "Fearful"),
    # 2 SIMILAR ("😩", "Weary"),
    # 2 SIMILAR ("😰", "Face With Open Mouth and Cold Sweat"),
                ("😱", "Screaming"),
                ("😳", "Flushed"),
                ("😵", "Dizzy"),
                ("😡", "Pouting"),
    # 2 SIMILAR ("😠", "Angry"),
                ("👿", "Imp"),
    # 2 SIMILAR ("😈", "Smiling Face With Horns"),
    # DULL      ("👦", "Boy"),
    # DULL      ("👧", "Girl"),
                ("👨", "Generic Man"),
                ("👩", "Generic Woman"),
                ("👴", "Older Man"),
                ("👵", "Older Woman"),
                ("👶", "A Baby"),
    # DULL      ("👱", "Person With Blond Hair"),
                ("👮", "Police Officer"),
    # OFFENSIVE ("👲", "Man With Gua Pi Mao"),
    # OFFENSIVE ("👳", "Man With Turban"),
                ("👷", "Trade Worker"),
                ("👸", "Princess"),
                ("💂", "Guardsman"),
                ("🎅", "Santa Claus"),
                ("👼", "Baby Angel"),
                ("👯", "Bunny Women"),
    # DULL      ("💆", "Face Massage"),
    # DULL      ("💇", "Haircut"),
                ("👰", "Bride"),
    # DULL      ("🙍", "Person Frowning"),
    # DULL      ("🙎", "Person With Pouting"),
                ("🙅", "Block Gesture"),
                ("🙆", "OK Gesture"),
                ("💁", "Sass Gesture"),  # for reply standings
                ("🙋", "Raised Hand"),
                ("🙇", "Deep Bow"),
                ("🙌", "Praise Hands"),
                ("🙏", "Prayer Hands"),
    # DULL      ("👤", "Bust in Silhouette"),
    # DULL      ("👥", "Busts in Silhouette"),
    # DULL      ("🚶", "Pedestrian"),
    # DULL      ("🏃", "Runner"),
                ("💃", "Dancer"),
    # 2 SIMILAR ("💏", "Kiss"),
    # DULL      ("💑", "Heteronormative Couple"),
                ("👪", "Hetero Family"),
                ("👫", "Man & Woman"),
                ("👬", "Two Men"),
                ("👭", "Two Women"),
                ("💪", "Biceps"),
    # DULL      ("👈", "White Left Pointing Backhand Index"),
    # DULL      ("👉", "White Right Pointing Backhand Index"),
                ("👆", "Pointing Hand"),
    # DULL      ("👇", "White Down Pointing Backhand Index"),
                ("✊", "Fist Hand"),
                ("✋", "Palm Hand"),
                ("👊", "Fist Hand"),
                ("👌", "OK Hand"),
                ("👍", "Thumbs Up"),
                ("👎", "Thumbs Down"),
    # UI USES   ("👋", "Waving Hand Sign"),  # for the welcome pages
                ("👏", "Clappy Hands"),
    # DULL      ("👐", "Open Hands Sign"),
                ("💅", "Nail Polish"),
                ("👣", "Footprints"),
    # UI USES   ("👀", "Eyes"),  # for the draw pages
                ("👂", "Ear"),
                ("👃", "Nose"),
                ("👅", "Tongue"),
                ("👄", "Mouth"),
    # 2 SIMILAR ("💋", "Kiss Mark"),
                ("💘", "Arrow Heart"),
    # 2 SIMILAR ("💓", "Beating Heart"),
                ("💔", "Broken Heart"),
    # 2 SIMILAR ("💕", "Two Hearts"),
                ("💖", "Sparkling Heart"),
    # 2 SIMILAR ("💗", "Growing Heart"),
    # 2 SIMILAR ("💙", "Blue Heart"),
    # 2 SIMILAR ("💚", "Green Heart"),
    # 2 SIMILAR ("💛", "Yellow Heart"),
    # 2 SIMILAR ("💜", "Purple Heart"),
    # 2 SIMILAR ("💝", "Heart With Ribbon"),
    # 2 SIMILAR ("💞", "Revolving Hearts"),
    # DULL      ("💟", "Heart Decoration"),
                ("💌", "Love Letter"),
                ("💧", "Droplet"),
                ("💤", "Sleeping"),
    # DULL      ("💢", "Anger"),
                ("💣", "Bomb"),
                ("💥", "Explosion"),
                ("💦", "Splashing"),
                ("💨", "Dash"),
                ("💫", "Shooting Star"),
    # DULL      ("💬", "Speech Balloon"),
    # DULL      ("💭", "Thought Balloon"),
                ("👓", "Eyeglasses"),
                ("👔", "Necktie"),
    # DULL      ("👕", "T-Shirt"),
    # DULL      ("👖", "Jeans"),
    # DULL      ("👗", "Dress"),
    # DULL      ("👘", "Kimono"),
                ("👙", "Bikini"),
    # DULL      ("👚", "Womans Clothes"),
    # DULL      ("👛", "Purse"),
                ("👜", "Handbag"),
    # DULL      ("👝", "Pouch"),
    # DULL      ("🎒", "School Satchel"),
    # DULL      ("👞", "Mans Shoe"),
                ("👟", "Runners"),
                ("👠", "Heels"),
    # DULL      ("👡", "Womans Sandal"),
    # DULL      ("👢", "Womans Boots"),
    # UI USES   ("👑", "Crown"),  # for the break pages
                ("👒", "Lady Hat"),
                ("🎩", "Top Hat"),
                ("💄", "Lipstick"),
                ("💍", "Ring"),
                ("💎", "Gem"),
    # DULL      ("👹", "Japanese Ogre"),
    # DULL      ("👺", "Japanese Goblin"),
                ("👻", "Ghost"),
                ("💀", "Skull"),
                ("👽", "Gray Alien"),
                ("👾", "Space Invader"),
                ("💩", "Pile of Poo"),
                ("🐵", "Monkey"),
                ("🙈", "See No Evil"),
                ("🙉", "Hear No Evil"),
                ("🙊", "Speak No Evil"),
    # OFFENSIVE ("🐒", "Monkey"),
                ("🐶", "Dog"),
    # DULL      ("🐕", "Dog"),
    # DULL      ("🐩", "Poodle"),
                ("🐺", "Wolf"),
    # UI USES   ("🐱", "Cat"),
    # UI USES   ("😸", "Grinning Cat Face With Smiling Eyes"),
    # UI USES   ("😹", "Cat Face With Tears of Joy"),
    # UI USES   ("😺", "Smiling Cat Face With Open Mouth"),
    # UI USES   ("😻", "Smiling Cat Face With Heart-Shaped Eyes"),
    # UI USES   ("😼", "Cat Face With Wry Smile"),
    # UI USES   ("😽", "Kissing Cat Face With Closed Eyes"),
    # UI USES   ("😾", "Pouting Cat Face")
    # UI USES   ("😿", "Crying Cat Face")
    # UI USES   ("🙀", "Weary Cat Face")
    # DULL      ("🐈", "Cat"),
                ("🐯", "Tiger"),
    # DULL      ("🐅", "Tiger"),
    # DULL      ("🐆", "Leopard"),
                ("🐴", "Horse"),
    # DULL      ("🐎", "Horse"),
                ("🐮", "Cow"),
    # DULL      ("🐂", "Ox"),
    # DULL      ("🐃", "Water Buffalo"),
    # DULL      ("🐄", "Cow"),
    # OFFENSIVE ("🐷", "Pig"),
    # DULL      ("🐖", "Pig"),
    # DULL      ("🐗", "Boar"),
    # DULL      ("🐽", "Pig Nose"),
    # DULL      ("🐏", "Ram"),
                ("🐑", "Sheep"),
    # DULL      ("🐐", "Goat"),
    # DULL      ("🐪", "Dromedary Camel"),
    # DULL      ("🐫", "Bactrian Camel"),
    # DULL      ("🐘", "Elephant"),
                ("🐭", "Mouse"),
    # DULL      ("🐁", "Mouse"),
    # DULL      ("🐀", "Rat"),
                ("🐹", "Hamster"),
                ("🐰", "Rabbit"),
    # DULL      ("🐇", "Rabbit"),
                ("🐻", "Bear"),
                ("🐨", "Koala"),
                ("🐼", "Panda"),
    # DULL      ("🐾", "Paw Prints"),
                ("🐔", "Chicken"),
    # DULL      ("🐓", "Rooster"),
                ("🐣", "Hatching Chick"),
                ("🐤", "Chick"),
    # 2 SIMILAR ("🐥", "Front-Facing Baby Chick"),
                ("🐦", "Bird"),
                ("🐧", "Penguin"),
                ("🐸", "Frog"),
    # DULL      ("🐊", "Crocodile"),
                ("🐢", "Turtle"),
                ("🐍", "Snake"),
                ("🐲", "Dragon"),
    # DULL      ("🐉", "Dragon"),
                ("🐳", "Whale"),
    # 2 SIMILAR ("🐋", "Whale"),
                ("🐬", "Dolphin"),
    # 2 SIMILAR ("🐟", "Fish"),
                ("🐠", "Fish"),
    # DULL      ("🐡", "Blowfish"),
                ("🐙", "Octopus"),
                ("🐚", "Shell"),
                ("🐌", "Snail"),
                ("🐛", "Bug"),
    # DULL      ("🐜", "Ant"),
                ("🐝", "Honeybee"),
    # DULL      ("🐞", "Lady Beetle"),
                ("💐", "Bouquet"),
                ("🌸", "Sakura"),
    # DULL      ("💮", "White Flower"),
                ("🌹", "Rose"),
    # DULL      ("🌺", "Hibiscus"),
                ("🌻", "Sunflower"),
    # DULL      ("🌼", "Blossom"),
                ("🌷", "Tulip"),
                ("🌱", "Seedling"),
    # DULL      ("🌲", "Evergreen Tree"),
    # DULL      ("🌳", "Deciduous Tree"),
                ("🌴", "Palm Tree"),
                ("🌵", "Cactus"),
    # DULL      ("🌾", "Ear of Rice"),
                ("🌿", "Herb"),
                ("🍀", "Clover"),
                ("🍁", "Maple Leaf"),
    # DULL      ("🍂", "Fallen Leaf"),
    # DULL      ("🍃", "Leaf Fluttering in Wind"),
                ("🍇", "Grapes"),
    # DULL      ("🍈", "Melon"),
                ("🍉", "Watermelon"),
    # 2 SIMILAR ("🍊", "Tangerine"),
                ("🍋", "Lemon"),
                ("🍌", "Banana"),
                ("🍍", "Pineapple"),
                ("🍎", "Red Apple"),
    # 2 SIMILAR ("🍏", "Green Apple"),
    # 2 SIMILAR ("🍐", "Pear"),
                ("🍑", "Peach"),
                ("🍒", "Cherries"),
                ("🍓", "Strawberry"),
    # 2 SIMILAR ("🍅", "Tomato"),
                ("🍆", "Aubergine?"),
                ("🌽", "Corn"),
                ("🍄", "Mushroom"),
    # DULL      ("🌰", "Chestnut"),
                ("🍞", "Bread"),
    # DULL      ("🍖", "Meat on Bone"),
    # DULL      ("🍗", "Poultry Leg"),
                ("🍔", "Hamburger"),
                ("🍟", "Freedom Fries"),
                ("🍕", "Pizza"),
    # DULL      ("🍲", "Pot of Food"),
    # DULL      ("🍱", "Bento Box"),
    # DULL      ("🍘", "Rice Cracker"),
                ("🍙", "Rice Ball"),
    # DULL      ("🍚", "Cooked Rice"),
    # DULL      ("🍛", "Curry and Rice"),
    # DULL      ("🍜", "Steaming Bowl"),
    # DULL      ("🍝", "Spaghetti"),
    # DULL      ("🍠", "Roasted Sweet Potato"),
    # DULL      ("🍢", "Oden"),
    # DULL      ("🍣", "Sushi"),
    # DULL      ("🍤", "Fried Shrimp"),
    # DULL      ("🍥", "Fish Cake With Swirl Design"),
    # DULL      ("🍡", "Dango"),
    # DULL      ("🍦", "Soft Ice Cream"),
    # DULL      ("🍧", "Shaved Ice"),
    # DULL      ("🍨", "Ice Cream"),
                ("🍩", "Doughnut"),
                ("🍪", "Cookie"),
    # DULL      ("🎂", "Birthday Cake"),
                ("🍰", "Shortcake"),
    # DULL      ("🍫", "Chocolate Bar"),
    # DULL      ("🍬", "Candy"),
                ("🍭", "Lollipop"),
    # DULL      ("🍮", "Custard"),
    # DULL      ("🍯", "Honey Pot"),
                ("🍼", "Baby Bottle"),
    # DULL      ("🍵", "Teacup Without Handle"),
    # DULL      ("🍶", "Sake Bottle and Cup"),
                ("🍷", "Wine Glass"),
    # 2 SIMILAR ("🍸", "Cocktail Glass"),
                ("🍹", "Tropical Drink"),
                ("🍺", "Beer"),
    # 2 SIMILAR ("🍻", "Clinking Beer Mugs"),
                ("🍴", "Fork & Knife"),
    # DULL      ("🍳", "Cooking"),
    # DULL      ("🌍", "Earth Globe Europe-Africa"),
    # DULL      ("🌎", "Earth Globe Americas"),
    # DULL      ("🌏", "Earth Globe Asia-Australia"),
    # DULL      ("🌐", "Globe With Meridians"),
                ("🌋", "Volcano"),
    # DULL      ("🗻", "Mount Fuji"),
                ("🏠", "House"),
    # DULL      ("🏡", "House With Garden"),
                ("🏢", "Office"),
    # 2 SIMILAR ("🏣", "Japanese Post Office"),
    # 2 SIMILAR ("🏤", "European Post Office"),
                ("🏥", "Hospital"),
    # 2 SIMILAR ("🏦", "Bank"),
    # 2 SIMILAR ("🏨", "Hotel"),
    # 2 SIMILAR ("🏩", "Love Hotel"),
    # 2 SIMILAR ("🏪", "Convenience Store"),
    # 2 SIMILAR ("🏫", "School"),
    # 2 SIMILAR ("🏬", "Department Store"),
    # 2 SIMILAR ("🏭", "Factory"),
    # 2 SIMILAR ("🏯", "Japanese Castle"),
                ("🏰", "Castle"),
    # 2 SIMILAR ("💒", "Wedding"),
    # 2 SIMILAR ("🗼", "Tokyo Tower"),
    # 2 SIMILAR ("🗽", "Statue of Liberty"),
    # 2 SIMILAR ("🗾", "Silhouette of Japan"),
    # 2 SIMILAR ("🌁", "Foggy"),
    # 2 SIMILAR ("🌃", "Night With Stars"),
    # 2 SIMILAR ("🌄", "Sunrise Over Mountains"),
    # 2 SIMILAR ("🌅", "Sunrise"),
    # 2 SIMILAR ("🌆", "Cityscape at Dusk"),
    # 2 SIMILAR ("🌇", "Sunset Over Buildings"),
    # 2 SIMILAR ("🌉", "Bridge at Night"),
                ("🌊", "Big Wave"),
    # DULL      ("🗿", "Moyai"),
    # DULL      ("🌌", "Milky Way"),
    # DULL      ("🎠", "Carousel Horse"),
                ("🎡", "Ferris Wheel"),
                ("🎢", "Roller Coaster"),
    # DULL      ("💈", "Barber Pole"),
    # UI USES   ("🎪", "Circus Tent")  # venue checkins/adding
    # DULL      ("🎭", "Performing Arts"),
                ("🎨", "Palette"),
    # DULL      ("🎰", "Slot Machine"),
    # DULL      ("🚂", "Steam Locomotive"),
                ("🚃", "Tram"),
                ("🚄", "Fast Train"),
    # 2 SIMILAR ("🚅", "High-Speed Train With Bullet Nose"),
    # 2 SIMILAR ("🚆", "Train"),
    # 2 SIMILAR ("🚇", "Metro"),
    # 2 SIMILAR ("🚈", "Light Rail"),
    # 2 SIMILAR ("🚉", "Station"),
    # 2 SIMILAR ("🚊", "Tram"),
                ("🚝", "Monorail"),
    # 2 SIMILAR ("🚞", "Mountain Railway"),
    # 2 SIMILAR ("🚋", "Tram Car"),
    # 2 SIMILAR ("🚌", "Bus"),
                ("🚍", "Bus"),
    # 2 SIMILAR ("🚎", "Trolleybus"),
    # 2 SIMILAR ("🚏", "Bus Stop"),
    # 2 SIMILAR ("🚐", "Minibus"),
    # 2 SIMILAR ("🚑", "Ambulance"),
    # 2 SIMILAR ("🚒", "Fire Engine"),
    # 2 SIMILAR ("🚓", "Police Car"),
                ("🚔", "Police Car"),
    # 2 SIMILAR ("🚕", "Taxi"),
    # 2 SIMILAR ("🚖", "Oncoming Taxi"),
    # 2 SIMILAR ("🚗", "Automobile"),
                ("🚘", "Automobile"),
    # 2 SIMILAR ("🚙", "Recreational Vehicle"),
    # 2 SIMILAR ("🚚", "Delivery Truck"),
    # 2 SIMILAR ("🚛", "Articulated Lorry"),
    # 2 SIMILAR ("🚜", "Tractor"),
                ("🚲", "Bicycle"),
    # 2 SIMILAR ("🚳", "No Bicycles"),
                ("🚨", "Alert Light"),
    # 2 SIMILAR ("🔱", "Trident Emblem"),
                ("🚣", "Rowboat"),
    # DULL      ("🚤", "Speedboat"),
    # DULL      ("🚢", "Ship"),
    # DULL      ("💺", "Seat"),
                ("🚁", "Helicopter"),
    # DULL      ("🚟", "Suspension Railway"),
    # DULL      ("🚠", "Mountain Cableway"),
    # DULL      ("🚡", "Aerial Tramway"),
                ("🚀", "Rocket"),
    # DULL      ("🏧", "Automated Teller Machine"),
    # DULL      ("🚮", "Put Litter in Its Place Symbol"),
    # DULL      ("🚥", "Horizontal Traffic Light"),
                ("🚦", "Traffic Light"),
                ("🚧", "Hazard Sign"),
                ("🚫", "No Entry Sign"),
    # DULL      ("🚭", "No Smoking Symbol"),
    # DULL      ("🚯", "Do Not Litter Symbol"),
    # DULL      ("🚰", "Potable Water Symbol"),
    # DULL      ("🚱", "Non-Potable Water Symbol"),
                ("🚷", "No Pedestrians"),
    # DULL      ("🚸", "Children Crossing"),
    # DULL      ("🚹", "Mens Symbol"),
    # DULL      ("🚺", "Womens Symbol"),
                ("🚻", "Restroom"),
    # DULL      ("🚼", "Baby Symbol"),
    # DULL      ("🚾", "Water Closet"),
    # DULL      ("🛂", "Passport Control"),
    # DULL      ("🛃", "Customs"),
    # DULL      ("🛄", "Baggage Claim"),
    # DULL      ("🛅", "Left Luggage"),
    # DULL      ("🚪", "Door"),
                ("🚽", "Toilet"),
                ("🚿", "Shower"),
                ("🛀", "Bath"),
    # DULL      ("🛁", "Bathtub"),
                ("⏳", "Hourglass"),
    # USED IN UI (tournaments overview) ("⏰", "Alarm Clock"),
    # DULL      ("⏱", "Stopwatch"),
    # DULL      ("⏲", "Timer Clock"),
    # DULL      ("🕛", "Clock Face Twelve O'Clock"),
    # DULL      ("🕧", "Clock Face Twelve-Thirty"),
    # DULL      ("🕐", "Clock Face One O'Clock"),
    # DULL      ("🕜", "Clock Face One-Thirty"),
    # DULL      ("🕑", "Clock Face Two O'Clock"),
    # DULL      ("🕝", "Clock Face Two-Thirty"),
    # DULL      ("🕒", "Clock Face Three O'Clock"),
    # DULL      ("🕞", "Clock Face Three-Thirty"),
    # DULL      ("🕓", "Clock Face Four O'Clock"),
    # DULL      ("🕟", "Clock Face Four-Thirty"),
    # DULL      ("🕔", "Clock Face Five O'Clock"),
    # DULL      ("🕠", "Clock Face Five-Thirty"),
    # DULL      ("🕕", "Clock Face Six O'Clock"),
    # DULL      ("🕡", "Clock Face Six-Thirty"),
    # DULL      ("🕖", "Clock Face Seven O'Clock"),
    # DULL      ("🕢", "Clock Face Seven-Thirty"),
    # DULL      ("🕗", "Clock Face Eight O'Clock"),
    # DULL      ("🕣", "Clock Face Eight-Thirty"),
    # DULL      ("🕘", "Clock Face Nine O'Clock"),
    # DULL      ("🕤", "Clock Face Nine-Thirty"),
    # DULL      ("🕙", "Clock Face Ten O'Clock"),
    # DULL      ("🕥", "Clock Face Ten-Thirty"),
    # DULL      ("🕚", "Clock Face Eleven O'Clock"),
    # DULL      ("🕦", "Clock Face Eleven-Thirty"),
    # DULL      ("⛎", "Ophiuchus"),
                ("🌑", "New Moon"),
    # DULL      ("🌒", "Waxing Crescent Moon Symbol"),
    # DULL      ("🌓", "First Quarter Moon Symbol"),
    # DULL      ("🌔", "Waxing Gibbous Moon Symbol"),
                ("🌕", "Full Moon"),
    # DULL      ("🌖", "Waning Gibbous Moon Symbol"),
                ("🌗", "Half Moon"),
    # DULL      ("🌘", "Waning Crescent Moon Symbol"),
    # DULL      ("🌙", "Crescent Moon"),
    # OFFENSIVE ("🌚", "New Moon With"),
    # DULL      ("🌛", "First Quarter Moon With"),
    # DULL      ("🌜", "Last Quarter Moon With"),
    # DULL      ("🌝", "Full Moon With"),
                ("🌞", "Sun"),
    # DULL      ("🌀", "Cyclone"),
                ("🌈", "Rainbow"),
    # DULL      ("🌂", "Umbrella"),
                ("🌟", "Glowing Star"),
    # DULL      ("🌠", "Shooting Star"),
                ("🔥", "Fire"),
                ("🎃", "Jack O Lantern"),
                ("🎄", "Christmas Tree"),
    # DULL      ("🎆", "Fireworks"),
    # DULL      ("🎇", "Firework Sparkler"),
    # DULL      ("✨", "Sparkles"),
                ("🎈", "Balloon"),
                ("🎉", "Party Popper"),
    # DULL      ("🎊", "Confetti Ball"),
    # DULL      ("🎋", "Tanabata Tree"),
    # DULL      ("🎌", "Crossed Flags"),
    # DULL      ("🎍", "Pine Decoration"),
    # DULL      ("🎎", "Japanese Dolls"),
    # DULL      ("🎏", "Carp Streamer"),
    # DULL      ("🎐", "Wind Chime"),
    # DULL      ("🎑", "Moon Viewing Ceremony"),
                ("🎓", "Graduation Cap"),
                ("🎯", "Bullseye"),
    # DULL      ("🎴", "Flower Playing Cards"),
                ("🎀", "Ribbon"),
    # DULL      ("🎁", "Wrapped Present"),
    # DULL      ("🎫", "Ticket"),
                ("🏀", "Basketball"),
                ("🏈", "USA Football"),
    # 2 SIMILAR ("🏉", "Rugby Football"),
                ("🎾", "Tennis Ball"),
                ("🎱", "Billiards"),
    # 2 SIMILAR ("🎳", "Bowling"),
    # DULL      ("🎣", "Fishing Pole and Fish"),
    # DULL      ("🎽", "Running Shirt With Sash"),
    # DULL      ("🎿", "Ski and Ski Boot"),
    # DULL      ("🏂", "Snowboarder"),
    # DULL      ("🏄", "Surfer"),
    # DULL      ("🏇", "Horse Racing"),
                ("🏊", "Swimmer"),
    # DULL      ("🚴", "Bicyclist"),
    # DULL      ("🚵", "Mountain Bicyclist"),
    # UI USES   ("🏆", "Trophy")  # for adding new tournament/list of tournaments
                ("🎮", "Video Game"),
                ("🎲", "Dice"),
    # DULL      ("🃏", "Playing Card Black Joker"),
    # DULL      ("🔇", "Speaker With Cancellation Stroke"),
    # DULL      ("🔈", "Speaker"),
    # DULL      ("🔉", "Speaker With One Sound Wave"),
    # DULL      ("🔊", "Speaker With Three Sound Waves"),
    # UI USES   ("📢", "Public Address Loudspeaker"),  # for public config settings
                ("📣", "Megaphone"),
                ("📯", "Horn"),
                ("🔔", "Bell"),
    #           ("🔕", "Bell With Cancellation Stroke"),
    # DULL      ("🔀", "Twisted Rightwards Arrows"),
    # DULL      ("🔁", "Clockwise Rightwards and Leftwards Open Circle Arrows"),
    # DULL      ("🔂", "Clockwise Rightwards and Leftwards Open Circle Arrows With Circled One Overlay"),
    # DULL      ("⏩", "Black Right-Pointing Double Triangle"),
    # DULL      ("⏭", "Black Right-Pointing Double Triangle With Vertical Bar"),
    # DULL      ("⏯", "Black Right-Pointing Triangle With Double Vertical Bar"),
    # DULL      ("⏪", "Black Left-Pointing Double Triangle"),
    # DULL      ("⏮", "Black Left-Pointing Double Triangle With Vertical Bar"),
    # DULL      ("🔼", "Up-Pointing Small Red Triangle"),
    # DULL      ("⏫", "Black Up-Pointing Double Triangle"),
    # DULL      ("🔽", "Down-Pointing Small Red Triangle"),
    # DULL      ("⏬", "Black Down-Pointing Double Triangle"),
    # DULL      ("🎼", "Musical Score"),
    # DULL      ("🎵", "Musical Note"),
                ("🎶", "Music Notes"),
                ("🎤", "Microphone"),
    # DULL      ("🎧", "Headphone"),
    # DULL      ("🎷", "Saxophone"),
    # DULL      ("🎸", "Guitar"),
                ("🎹", "Keyboard"),
                ("🎺", "Trumpet"),
                ("🎻", "Violin"),
                ("📻", "Radio"),
                ("📱", "Internet Phone"),
    # DULL      ("📳", "Vibration Mode"),
    # DULL      ("📴", "Mobile Phone Off"),
    # 2 SIMILAR ("📲", "Mobile Phone With Rightwards Arrow at Left"),
    # DULL      ("📵", "No Mobile Phones"),
                ("📞", "Telephone"),
    # DULL      ("🔟", "Keycap Ten"),
    # DULL      ("📶", "Antenna With Bars"),
    # DULL      ("📟", "Pager"),
    # DULL      ("📠", "Fax Machine"),
                ("🔋", "Battery"),
                ("🔌", "Plug"),
    # DULL      ("💻", "Personal Computer"),
    # DULL      ("💽", "Minidisc"),
                ("💾", "Floppy"),
                ("💿", "Compact Disc"),
    # DULL      ("📀", "DVD"),
    # DULL      ("🎥", "Movie Camera"),
    # DULL      ("🎦", "Cinema"),
                ("🎬", "Clapper"),
    # UI USES   ("📺", "Television"),
                ("📷", "Camera"),
    # DULL      ("📹", "Video Camera"),
    # DULL      ("📼", "Videocassette"),
    # DULL      ("🔅", "Low Brightness Symbol"),
    # DULL      ("🔆", "High Brightness Symbol"),
                ("🔍", "Magnifying Glass"),
    # DULL      ("🔎", "Right-Pointing Magnifying Glass"),
    # DULL      ("🔬", "Microscope"),
                ("🔭", "Telescope"),
    # DULL      ("📡", "Satellite Dish"),
                ("💡", "Light Bulb"),
    # DULL      ("🔦", "Electric Torch"),
    # DULL      ("🏮", "Izakaya Lantern"),
    # 2 SIMILAR ("📔", "Notebook With Decorative Cover"),
                ("📕", "Closed Book"),
    # 2 SIMILAR ("📖", "Open Book"),
    # 2 SIMILAR ("📗", "Green Book"),
    # 2 SIMILAR ("📘", "Blue Book"),
    # 2 SIMILAR ("📙", "Orange Book"),
    # 2 SIMILAR ("📚", "Books"),
    # 2 SIMILAR ("📓", "Notebook"),
    # 2 SIMILAR ("📒", "Ledger"),
    # 2 SIMILAR ("📃", "Page With Curl"),
    # 2 SIMILAR ("📜", "Scroll"),
    # 2 SIMILAR ("📄", "Page Facing Up"),
                ("📰", "Newspaper"),
    # 2 SIMILAR ("📑", "Bookmark Tabs"),
    # 2 SIMILAR ("🔖", "Bookmark"),
                ("💰", "Money Bag"),
    # 2 SIMILAR ("💴", "Banknote With Yen Sign"),
    # 2 SIMILAR ("💵", "Banknote With Dollar Sign"),
    # 2 SIMILAR ("💶", "Banknote With Euro Sign"),
    # 2 SIMILAR ("💷", "Banknote With Pound Sign"),
                ("💸", "Flying Money"),
    # DULL      ("💱", "Currency Exchange"),
    # DULL      ("💲", "Heavy Dollar Sign"),
    # DULL      ("💳", "Credit Card"),
    # DULL      ("💹", "Chart With Upwards Trend and Yen Sign"),
    # DULL      ("📧", "E-Mail Symbol"),
    # DULL      ("📨", "Incoming Envelope"),
    # DULL      ("📩", "Envelope With Downwards Arrow Above"),
    # DULL      ("📤", "Outbox Tray"),
    # DULL      ("📥", "Inbox Tray"),
                ("📦", "Package"),
                ("📫", "Mailbox"),
    # DULL      ("📪", "Closed Mailbox With Lowered Flag"),
    # DULL      ("📬", "Open Mailbox With Raised Flag"),
    # DULL      ("📭", "Open Mailbox With Lowered Flag"),
    # DULL      ("📮", "Postbox"),
    # DULL      ("📝", "Memo"),
                ("💼", "Briefcase"),
    # DULL      ("📁", "File Folder"),
    # DULL      ("📂", "Open File Folder"),
                ("📅", "Calendar"),
    # DULL      ("📆", "Tear-Off Calendar"),
    # DULL      ("📇", "Card Index"),
    # DULL      ("📈", "Chart With Upwards Trend"),
    # DULL      ("📉", "Chart With Downwards Trend"),
    # DULL      ("📊", "Bar Chart"),
    # DULL      ("📋", "Clipboard"),
    # DULL      ("📌", "Pushpin"),
    # DULL      ("📍", "Round Pushpin"),
                ("📎", "Paperclip"),
                ("📏", "Straight Ruler"),
                ("📐", "Triangle Ruler"),
    # DULL      ("📛", "Name Badge"),
                ("🔒", "Lock"),
    # 2 SIMILAR ("🔓", "Open Lock"),
    #           ("🔏", "Lock With Ink Pen"),
    #           ("🔐", "Closed Lock With Key"),
                ("🔑", "Key"),
    # DULL      ("🔨", "Hammer"),
                ("🔧", "Wrench"),
                ("🔩", "Calipers"),
    # DULL      ("🔗", "Link Symbol"),
                ("💉", "Syringe"),
                ("💊", "Pill"),
                ("🔪", "Chef Knife"),
                ("🔫", "Pistol"),
                ("🚬", "Durrie"),
                ("🏁", "Chequered Flag"),
    # DULL      ("🚩", "Triangular Flag on Post"),
    # DULL      ("🇦🇫", "Flag for Afghanistan"),
    # DULL      ("🇦🇽", "Flag for Åland Islands"),
    # DULL      ("🇦🇱", "Flag for Albania"),
    # DULL      ("🇩🇿", "Flag for Algeria"),
    # DULL      ("🇦🇸", "Flag for American Samoa"),
    # DULL      ("🇦🇩", "Flag for Andorra"),
    # DULL      ("🇦🇴", "Flag for Angola"),
    # DULL      ("🇦🇮", "Flag for Anguilla"),
    #           ("🇦🇶", "Flag for Antarctica"),
    # DULL      ("🇦🇬", "Flag for Antigua & Barbuda"),
    # DULL      ("🇦🇷", "Flag for Argentina"),
    # DULL      ("🇦🇲", "Flag for Armenia"),
    # DULL      ("🇦🇼", "Flag for Aruba"),
    # DULL      ("🇦🇨", "Flag for Ascension Island"),
    #           ("🇦🇺", "Flag for Australia"),
    #           ("🇦🇹", "Flag for Austria"),
    # DULL      ("🇦🇿", "Flag for Azerbaijan"),
    # DULL      ("🇧🇸", "Flag for Bahamas"),
    # DULL      ("🇧🇭", "Flag for Bahrain"),
    # DULL      ("🇧🇩", "Flag for Bangladesh"),
    # DULL      ("🇧🇧", "Flag for Barbados"),
    # DULL      ("🇧🇾", "Flag for Belarus"),
    # DULL      ("🇧🇪", "Flag for Belgium"),
    # DULL      ("🇧🇿", "Flag for Belize"),
    # DULL      ("🇧🇯", "Flag for Benin"),
    # DULL      ("🇧🇲", "Flag for Bermuda"),
    # DULL      ("🇧🇹", "Flag for Bhutan"),
    # DULL      ("🇧🇴", "Flag for Bolivia"),
    # DULL      ("🇧🇦", "Flag for Bosnia & Herzegovina"),
    # DULL      ("🇧🇼", "Flag for Botswana"),
    # DULL      ("🇧🇻", "Flag for Bouvet Island"),
    #           ("🇧🇷", "Flag for Brazil"),
    # DULL      ("🇮🇴", "Flag for British Indian Ocean Territory"),
    # DULL      ("🇻🇬", "Flag for British Virgin Islands"),
    # DULL      ("🇧🇳", "Flag for Brunei"),
    # DULL      ("🇧🇬", "Flag for Bulgaria"),
    # DULL      ("🇧🇫", "Flag for Burkina Faso"),
    # DULL      ("🇧🇮", "Flag for Burundi"),
    # DULL      ("🇰🇭", "Flag for Cambodia"),
    # DULL      ("🇨🇲", "Flag for Cameroon"),
    #           ("🇨🇦", "Flag for Canada"),
    # DULL      ("🇮🇨", "Flag for Canary Islands"),
    # DULL      ("🇨🇻", "Flag for Cape Verde"),
    # DULL      ("🇧🇶", "Flag for Caribbean Netherlands"),
    # DULL      ("🇰🇾", "Flag for Cayman Islands"),
    # DULL      ("🇨🇫", "Flag for Central African Republic"),
    # DULL      ("🇪🇦", "Flag for Ceuta & Melilla"),
    # DULL      ("🇹🇩", "Flag for Chad"),
    #           ("🇨🇱", "Flag for Chile"),
    #           ("🇨🇳", "Flag for China"),
    # DULL      ("🇨🇽", "Flag for Christmas Island"),
    # DULL      ("🇨🇵", "Flag for Clipperton Island"),
    # DULL      ("🇨🇨", "Flag for Cocos Islands"),
    # DULL      ("🇨🇴", "Flag for Colombia"),
    # DULL      ("🇰🇲", "Flag for Comoros"),
    # DULL      ("🇨🇬", "Flag for Congo - Brazzaville"),
    # DULL      ("🇨🇩", "Flag for Congo - Kinshasa"),
    # DULL      ("🇨🇰", "Flag for Cook Islands"),
    # DULL      ("🇨🇷", "Flag for Costa Rica"),
    # DULL      ("🇨🇮", "Flag for Côte D’Ivoire"),
    # DULL      ("🇭🇷", "Flag for Croatia"),
    # DULL      ("🇨🇺", "Flag for Cuba"),
    # DULL      ("🇨🇼", "Flag for Curaçao"),
    # DULL      ("🇨🇾", "Flag for Cyprus"),
    #           ("🇨🇿", "Flag for Czech Republic"),
    #           ("🇩🇰", "Flag for Denmark"),
    # DULL      ("🇩🇬", "Flag for Diego Garcia"),
    # DULL      ("🇩🇯", "Flag for Djibouti"),
    # DULL      ("🇩🇲", "Flag for Dominica"),
    # DULL      ("🇩🇴", "Flag for Dominican Republic"),
    # DULL      ("🇪🇨", "Flag for Ecuador"),
    #           ("🇪🇬", "Flag for Egypt"),
    # DULL      ("🇸🇻", "Flag for El Salvador"),
    # DULL      ("🇬🇶", "Flag for Equatorial Guinea"),
    # DULL      ("🇪🇷", "Flag for Eritrea"),
    # DULL      ("🇪🇪", "Flag for Estonia"),
    # DULL      ("🇪🇹", "Flag for Ethiopia"),
    #           ("🇪🇺", "Flag for European Union"),
    # DULL      ("🇫🇰", "Flag for Falkland Islands"),
    # DULL      ("🇫🇴", "Flag for Faroe Islands"),
    # DULL      ("🇫🇯", "Flag for Fiji"),
    # DULL      ("🇫🇮", "Flag for Finland"),
    #           ("🇫🇷", "Flag for France"),
    # DULL      ("🇬🇫", "Flag for French Guiana"),
    # DULL      ("🇵🇫", "Flag for French Polynesia"),
    # DULL      ("🇹🇫", "Flag for French Southern Territories"),
    # DULL      ("🇬🇦", "Flag for Gabon"),
    # DULL      ("🇬🇲", "Flag for Gambia"),
    # DULL      ("🇬🇪", "Flag for Georgia"),
    #           ("🇩🇪", "Flag for Germany"),
    # DULL      ("🇬🇭", "Flag for Ghana"),
    # DULL      ("🇬🇮", "Flag for Gibraltar"),
    #           ("🇬🇷", "Flag for Greece"),
    # DULL      ("🇬🇱", "Flag for Greenland"),
    # DULL      ("🇬🇩", "Flag for Grenada"),
    # DULL      ("🇬🇵", "Flag for Guadeloupe"),
    # DULL      ("🇬🇺", "Flag for Guam"),
    # DULL      ("🇬🇹", "Flag for Guatemala"),
    # DULL      ("🇬🇬", "Flag for Guernsey"),
    # DULL      ("🇬🇳", "Flag for Guinea"),
    # DULL      ("🇬🇼", "Flag for Guinea-Bissau"),
    # DULL      ("🇬🇾", "Flag for Guyana"),
    # DULL      ("🇭🇹", "Flag for Haiti"),
    # DULL      ("🇭🇲", "Flag for Heard & McDonald Islands"),
    # DULL      ("🇭🇳", "Flag for Honduras"),
    # DULL      ("🇭🇰", "Flag for Hong Kong"),
    # DULL      ("🇭🇺", "Flag for Hungary"),
    # DULL      ("🇮🇸", "Flag for Iceland"),
    #           ("🇮🇳", "Flag for India"),
    #           ("🇮🇩", "Flag for Indonesia"),
    #           ("🇮🇷", "Flag for Iran"),
    #           ("🇮🇶", "Flag for Iraq"),
    #           ("🇮🇪", "Flag for Ireland"),
    # DULL      ("🇮🇲", "Flag for Isle of Man"),
    # DULL      ("🇮🇱", "Flag for Israel"),
    #           ("🇮🇹", "Flag for Italy"),
    # DULL      ("🇯🇲", "Flag for Jamaica"),
    #           ("🇯🇵", "Flag for Japan"),
    # DULL      ("🇯🇪", "Flag for Jersey"),
    # DULL      ("🇯🇴", "Flag for Jordan"),
    # DULL      ("🇰🇿", "Flag for Kazakhstan"),
    # DULL      ("🇰🇪", "Flag for Kenya"),
    # DULL      ("🇰🇮", "Flag for Kiribati"),
    # DULL      ("🇽🇰", "Flag for Kosovo"),
    # DULL      ("🇰🇼", "Flag for Kuwait"),
    # DULL      ("🇰🇬", "Flag for Kyrgyzstan"),
    # DULL      ("🇱🇦", "Flag for Laos"),
    # DULL      ("🇱🇻", "Flag for Latvia"),
    # DULL      ("🇱🇧", "Flag for Lebanon"),
    # DULL      ("🇱🇸", "Flag for Lesotho"),
    # DULL      ("🇱🇷", "Flag for Liberia"),
    # DULL      ("🇱🇾", "Flag for Libya"),
    # DULL      ("🇱🇮", "Flag for Liechtenstein"),
    # DULL      ("🇱🇹", "Flag for Lithuania"),
    # DULL      ("🇱🇺", "Flag for Luxembourg"),
    # DULL      ("🇲🇴", "Flag for Macau"),
    # DULL      ("🇲🇰", "Flag for Macedonia"),
    # DULL      ("🇲🇬", "Flag for Madagascar"),
    # DULL      ("🇲🇼", "Flag for Malawi"),
    # DULL      ("🇲🇾", "Flag for Malaysia"),
    # DULL      ("🇲🇻", "Flag for Maldives"),
    # DULL      ("🇲🇱", "Flag for Mali"),
    # DULL      ("🇲🇹", "Flag for Malta"),
    # DULL      ("🇲🇭", "Flag for Marshall Islands"),
    # DULL      ("🇲🇶", "Flag for Martinique"),
    # DULL      ("🇲🇷", "Flag for Mauritania"),
    # DULL      ("🇲🇺", "Flag for Mauritius"),
    # DULL      ("🇾🇹", "Flag for Mayotte"),
    #           ("🇲🇽", "Flag for Mexico"),
    # DULL      ("🇫🇲", "Flag for Micronesia"),
    # DULL      ("🇲🇩", "Flag for Moldova"),
    # DULL      ("🇲🇨", "Flag for Monaco"),
    # DULL      ("🇲🇳", "Flag for Mongolia"),
    # DULL      ("🇲🇪", "Flag for Montenegro"),
    # DULL      ("🇲🇸", "Flag for Montserrat"),
    # DULL      ("🇲🇦", "Flag for Morocco"),
    # DULL      ("🇲🇿", "Flag for Mozambique"),
    # DULL      ("🇲🇲", "Flag for Myanmar"),
    # DULL      ("🇳🇦", "Flag for Namibia"),
    # DULL      ("🇳🇷", "Flag for Nauru"),
    # DULL      ("🇳🇵", "Flag for Nepal"),
    # DULL      ("🇳🇱", "Flag for Netherlands"),
    # DULL      ("🇳🇨", "Flag for New Caledonia"),
    #           ("🇳🇿", "Flag for New Zealand"),
    # DULL      ("🇳🇮", "Flag for Nicaragua"),
    # DULL      ("🇳🇪", "Flag for Niger"),
    # DULL      ("🇳🇬", "Flag for Nigeria"),
    # DULL      ("🇳🇺", "Flag for Niue"),
    # DULL      ("🇳🇫", "Flag for Norfolk Island"),
    # DULL      ("🇲🇵", "Flag for Northern Mariana Islands"),
    # DULL      ("🇰🇵", "Flag for North Korea"),
    #           ("🇳🇴", "Flag for Norway"),
    # DULL      ("🇴🇲", "Flag for Oman"),
    # DULL      ("🇵🇰", "Flag for Pakistan"),
    # DULL      ("🇵🇼", "Flag for Palau"),
    #           ("🇵🇸", "Flag for Palestinian Territories"),
    # DULL      ("🇵🇦", "Flag for Panama"),
    # DULL      ("🇵🇬", "Flag for Papua New Guinea"),
    # DULL      ("🇵🇾", "Flag for Paraguay"),
    #           ("🇵🇪", "Flag for Peru"),
    # DULL      ("🇵🇭", "Flag for Philippines"),
    # DULL      ("🇵🇳", "Flag for Pitcairn Islands"),
    # DULL      ("🇵🇱", "Flag for Poland"),
    # DULL      ("🇵🇹", "Flag for Portugal"),
    # DULL      ("🇵🇷", "Flag for Puerto Rico"),
    # DULL      ("🇶🇦", "Flag for Qatar"),
    # DULL      ("🇷🇪", "Flag for Réunion"),
    # DULL      ("🇷🇴", "Flag for Romania"),
    #           ("🇷🇺", "Flag for Russia"),
    # DULL      ("🇷🇼", "Flag for Rwanda"),
    # DULL      ("🇼🇸", "Flag for Samoa"),
    # DULL      ("🇸🇲", "Flag for San Marino"),
    # DULL      ("🇸🇹", "Flag for São Tomé & Príncipe"),
    # DULL      ("🇸🇦", "Flag for Saudi Arabia"),
    # DULL      ("🇸🇳", "Flag for Senegal"),
    # DULL      ("🇷🇸", "Flag for Serbia"),
    # DULL      ("🇸🇨", "Flag for Seychelles"),
    # DULL      ("🇸🇱", "Flag for Sierra Leone"),
    # DULL      ("🇸🇬", "Flag for Singapore"),
    # DULL      ("🇸🇽", "Flag for Sint Maarten"),
    # DULL      ("🇸🇰", "Flag for Slovakia"),
    # DULL      ("🇸🇮", "Flag for Slovenia"),
    # DULL      ("🇸🇧", "Flag for Solomon Islands"),
    # DULL      ("🇸🇴", "Flag for Somalia"),
    #           ("🇿🇦", "Flag for South Africa"),
    # DULL      ("🇬🇸", "Flag for South Georgia & South Sandwich Islands"),
    #           ("🇰🇷", "Flag for South Korea"),
    # DULL      ("🇸🇸", "Flag for South Sudan"),
    #           ("🇪🇸", "Flag for Spain"),
    # DULL      ("🇱🇰", "Flag for Sri Lanka"),
    # DULL      ("🇧🇱", "Flag for St. Barthélemy"),
    # DULL      ("🇸🇭", "Flag for St. Helena"),
    # DULL      ("🇰🇳", "Flag for St. Kitts & Nevis"),
    # DULL      ("🇱🇨", "Flag for St. Lucia"),
    # DULL      ("🇲🇫", "Flag for St. Martin"),
    # DULL      ("🇵🇲", "Flag for St. Pierre & Miquelon"),
    # DULL      ("🇻🇨", "Flag for St. Vincent & Grenadines"),
    # DULL      ("🇸🇩", "Flag for Sudan"),
    # DULL      ("🇸🇷", "Flag for Suriname"),
    # DULL      ("🇸🇯", "Flag for Svalbard & Jan Mayen"),
    # DULL      ("🇸🇿", "Flag for Swaziland"),
    #           ("🇸🇪", "Flag for Sweden"),
    #           ("🇨🇭", "Flag for Switzerland"),
    # DULL      ("🇸🇾", "Flag for Syria"),
    # DULL      ("🇹🇼", "Flag for Taiwan"),
    # DULL      ("🇹🇯", "Flag for Tajikistan"),
    # DULL      ("🇹🇿", "Flag for Tanzania"),
    # DULL      ("🇹🇭", "Flag for Thailand"),
    # DULL      ("🇹🇱", "Flag for Timor-Leste"),
    # DULL      ("🇹🇬", "Flag for Togo"),
    # DULL      ("🇹🇰", "Flag for Tokelau"),
    # DULL      ("🇹🇴", "Flag for Tonga"),
    # DULL      ("🇹🇹", "Flag for Trinidad & Tobago"),
    # DULL      ("🇹🇦", "Flag for Tristan Da Cunha"),
    # DULL      ("🇹🇳", "Flag for Tunisia"),
    #           ("🇹🇷", "Flag for Turkey"),
    # DULL      ("🇹🇲", "Flag for Turkmenistan"),
    # DULL      ("🇹🇨", "Flag for Turks & Caicos Islands"),
    # DULL      ("🇹🇻", "Flag for Tuvalu"),
    # DULL      ("🇺🇬", "Flag for Uganda"),
    # DULL      ("🇺🇦", "Flag for Ukraine"),
    # DULL      ("🇦🇪", "Flag for United Arab Emirates"),
    #           ("🇬🇧", "Flag for United Kingdom"),
    #           ("🇺🇸", "Flag for United States"),
    # DULL      ("🇺🇾", "Flag for Uruguay"),
    # DULL      ("🇺🇲", "Flag for U.S. Outlying Islands"),
    # DULL      ("🇻🇮", "Flag for U.S. Virgin Islands"),
    # DULL      ("🇺🇿", "Flag for Uzbekistan"),
    # DULL      ("🇻🇺", "Flag for Vanuatu"),
    #           ("🇻🇦", "Flag for Vatican City"),
    # DULL      ("🇻🇪", "Flag for Venezuela"),
    #           ("🇻🇳", "Flag for Vietnam"),
    # DULL      ("🇼🇫", "Flag for Wallis & Futuna"),
    # DULL      ("🇪🇭", "Flag for Western Sahara"),
    # DULL      ("🇾🇪", "Flag for Yemen"),
    # DULL      ("🇿🇲", "Flag for Zambia"),
    # DULL      ("🇿🇼", "Flag for Zimbabwe"),
    # DULL      ("🔃", "Clockwise Downwards and Upwards Open Circle Arrows"),
    # DULL      ("🔄", "Anticlockwise Downwards and Upwards Open Circle Arrows"),
    # DULL      ("🔙", "Back With Leftwards Arrow Above"),
    # DULL      ("🔚", "End With Leftwards Arrow Above"),
    # DULL      ("🔛", "On With Exclamation Mark With Left Right Arrow Above"),
    # DULL      ("🔜", "Soon With Rightwards Arrow Above"),
    # DULL      ("🔝", "Top With Upwards Arrow Above"),
    # DULL      ("🔰", "Japanese Symbol for Beginner"),
                ("🔮", "Crystal Ball"),
    # DULL      ("🔯", "Six Pointed Star With Middle Dot"),
    # DULL      ("✅", "White Heavy Check Mark"),
                ("❌", "Cross"),
    # DULL      ("❎", "Negative Squared Cross Mark"),
    # DULL      ("➕", "Heavy Plus Sign"),
    # DULL      ("➖", "Heavy Minus Sign"),
    # DULL      ("➗", "Heavy Division Sign"),
    # DULL      ("➰", "Curly Loop"),
    # DULL      ("➿", "Double Curly Loop"),
                ("❓", "Question"),
    # 2 SIMILAR ("❔", "White Question Mark Ornament"),
    # 2 SIMILAR ("❕", "White Exclamation Mark Ornament"),
    # UI USES   ("💯", "Hundred Points Symbol"),  # Speaker tab
                ("🔞", "Over Eighteen"),
    # DULL      ("🔠", "Input Symbol for Latin Capital Letters"),
    # DULL      ("🔡", "Input Symbol for Latin Small Letters"),
    # DULL      ("🔢", "Input Symbol for Numbers"),
    # DULL      ("🔣", "Input Symbol for Symbols"),
    # DULL      ("🔤", "Input Symbol for Latin Letters"),
    # DULL      ("🅰️", "Negative Squared Latin Capital Letter A"),
    # DULL      ("🆎", "Negative Squared AB"),
    # DULL      ("🅱️", "Negative Squared Latin Capital Letter B"),
    # DULL      ("🆑", "Squared CL"),
                ("🆒", "Cool Square"),
    # DULL      ("🆓", "Squared Free"),
    # DULL      ("🆔", "Squared ID"),
    # DULL      ("🆕", "Squared New"),
    # DULL      ("🆖", "Squared NG"),
    # DULL      ("🅾️", "Negative Squared Latin Capital Letter O"),
                ("🆗", "OK Square"),
                ("🆘", "SOS Square"),
    # DULL      ("🆙", "Squared Up With Exclamation Mark"),
    # DULL      ("🆚", "Squared Vs"),
    # DULL      ("🈁", "Squared Katakana Koko"),
    # DULL      ("🈂️", "Squared Katakana Sa"),
    # DULL      ("🈷️", "Squared CJK Unified Ideograph-6708"),
    # DULL      ("🈶", "Squared CJK Unified Ideograph-6709"),
    # DULL      ("🉐", "Circled Ideograph Advantage"),
    # DULL      ("🈹", "Squared CJK Unified Ideograph-5272"),
    # DULL      ("🈲", "Squared CJK Unified Ideograph-7981"),
    # DULL      ("🉑", "Circled Ideograph Accept"),
    # DULL      ("🈸", "Squared CJK Unified Ideograph-7533"),
    # DULL      ("🈴", "Squared CJK Unified Ideograph-5408"),
    # DULL      ("🈳", "Squared CJK Unified Ideograph-7a7a"),
    # DULL      ("🈺", "Squared CJK Unified Ideograph-55b6"),
    # DULL      ("🈵", "Squared CJK Unified Ideograph-6e80"),
    # UI USES   ("🔶", "Large Orange Diamond"),
    # DULL      ("🔷", "Large Blue Diamond"),
    # DULL      ("🔸", "Small Orange Diamond"),
    # DULL      ("🔹", "Small Blue Diamond"),
    # DULL      ("🔺", "Up-Pointing Red Triangle"),
    # DULL      ("🔻", "Down-Pointing Red Triangle"),
    # DULL      ("💠", "Diamond Shape With a Dot Inside"),
    # DULL      ("🔘", "Radio Button"),
    # DULL      ("🔲", "Black Square Button"),
    # DULL      ("🔳", "White Square Button"),
    # DULL      ("🔴", "Large Red Circle"),
    # DULL      ("🔵", "Large Blue Circle"),
    # ---------------------
    # Unicode    Version 6.1
    # ---------------------
    # 2 SIMILAR ("😀", "Grinning"),
    # 2 SIMILAR ("😗", "Kissing"),
                ("😙", "Smooch"),
                ("😑", "True Neutral"),
                ("😮", "Stunned"),
    # 2 SIMILAR ("😯", "Hushed"),
                ("😴", "Sleeping"),
                ("😛", "Tongue"),
    # 2 SIMILAR ("😕", "Confused"),
    # 2 SIMILAR ("😟", "Worried"),
    # 2 SIMILAR ("😦", "Frowning Face With Open Mouth"),
                ("😧", "Anguished"),
                ("😬", "Grimacing"),
    # ---------------------
    # Unicode    Version 7.0
    # ---------------------
    # 2 SIMILAR ("🙂", "Slightly Smiling"),
    # 2 SIMILAR ("🙁", "Slightly Frowning"),
                ("🕵", "Spy"),
    # DULL      ("🗣", "Speaking Head in Silhouette"),
    # DULL      ("🕴", "Man in Business Suit Levitating"),
                ("🖕", "Middle Finger"),
                ("🖖", "Vulcan Hand"),
    # 2 SIMILAR ("🖐", "Raised Hand With Fingers Splayed"),
                ("👁", "Eye"),
    # DULL      ("🕳", "Hole"),
    # DULL      ("🗯", "Right Anger Bubble"),
    # DULL      ("🕶", "Dark Sunglasses"),
                ("🛍", "Shopping Bags"),
                ("🐿", "Chipmunk"),
                ("🕊", "Peace Dove"),
                ("🕷", "Spider"),
                ("🕸", "Spider Web"),
                ("🏵", "Rosette"),
                ("🌶", "Hot Pepper"),
    # DULL      ("🍽", "Fork and Knife With Plate"),
    # DULL      ("🗺", "World Map"),
    # DULL      ("🏔", "Snow Capped Mountain"),
                ("🏕", "Camping"),
    # DULL      ("🏖", "Beach With Umbrella"),
    # DULL      ("🏜", "Desert"),
    # DULL      ("🏝", "Desert Island"),
    # DULL      ("🏞", "National Park"),
    # DULL      ("🏟", "Stadium"),
                ("🏛", "Architecture"),
    # DULL      ("🏗", "Building Construction"),
    # DULL      ("🏘", "House Buildings"),
    # DULL      ("🏙", "Cityscape"),
    # DULL      ("🏚", "Derelict House Building"),
    # DULL      ("🖼", "Frame With Picture"),
                ("🛢", "Oil Drum"),
    # DULL      ("🛣", "Motorway"),
    # DULL      ("🛤", "Railway Track"),
    # DULL      ("🛳", "Passenger Ship"),
                ("🛥", "Motor Boat"),
                ("🛩", "Airplane"),
    # DULL      ("🛫", "Airplane Departure"),
    # DULL      ("🛬", "Airplane Arriving"),
    # DULL      ("🛰", "Satellite"),
                ("🛎", "Service Bell"),
    # DULL      ("🛌", "Sleeping Accommodation"),
    # DULL      ("🛏", "Bed"),
    # DULL      ("🛋", "Couch and Lamp"),
                ("🕰", "Mantelpiece"),
                ("🌡", "Thermometer"),
    # DULL      ("🌤", "Small Cloud"),
    # DULL      ("🌥", "White Sun Behind Cloud"),
    # DULL      ("🌦", "White Sun Behind Cloud With Rain"),
    # DULL      ("🌧", "Cloud With Rain"),
    # DULL      ("🌨", "Cloud With Snow"),
                ("🌩", "Lightning"),
                ("🌪", "Tornado"),
    # DULL      ("🌫", "Fog"),
                ("🌬", "Blowing"),
                ("🎖", "Medal"),
                ("🎗", "Ribbon"),
                ("🎞", "Film"),
    # DULL      ("🎟", "Admission Tickets"),
                ("🏷", "Label"),
    # DULL      ("🏌", "Golfer"),
                ("🏋", "Lifting"),
    # DULL      ("🏎", "Racing Car"),
    # DULL      ("🏍", "Racing Motorcycle"),
                ("🏅", "Medal"),
                ("🕹", "Joystick"),
    # DULL      ("⏸", "Double Vertical Bar"),
    # DULL      ("⏹", "Black Square for Stop"),
    # DULL      ("⏺", "Black Circle for Record"),
                ("🎙", "Microphone"),
    # DULL      ("🎚", "Level Slider"),
    # DULL      ("🎛", "Control Knobs"),
                ("🖥", "Computer"),
                ("🖨", "Printer"),
    # DULL      ("🖱", "Three Button Mouse"),
                ("🖲", "Trackball"),
    # DULL      ("📽", "Film Projector"),
                ("📸", "Camera"),
                ("🕯", "Candle"),
                ("🗞", "Newspaper"),
    # DULL      ("🗳", "Ballot Box With Ballot"),
                ("🖋", "Fancy Pen"),
    # DULL      ("🖊", "Lower Left Ballpoint Pen"),
    # DULL      ("🖌", "Lower Left Paintbrush"),
    # DULL      ("🖍", "Lower Left Crayon"),
    # UI USES   ("🗂", "Card Index Dividers"),
    # DULL      ("🗒", "Spiral Note Pad"),
    # DULL      ("🗓", "Spiral Calendar Pad"),
    # DULL      ("🖇", "Linked Paperclips"),
    # DULL      ("🗃", "Card File Box"),
    # DULL      ("🗄", "File Cabinet"),
                ("🗑", "Trash Place"),
    # DULL      ("🗝", "Old Key"),
                ("🛠", "Hammer Wrench"),
    # DULL      ("🗜", "Compression"),
                ("🗡", "Dagger Knife"),
                ("🛡", "Shield"),
                ("🏳", "White Flag"),
                ("🏴", "Black Flag"),
    # DULL      ("🕉", "Om Symbol"),
    # DULL      ("🗨", "Left Speech Bubble"),
    # ---------------------
    # Unicode    Version 8.0
    # ---------------------
                ("🤗", "Hugging"),
                ("🤔", "Thinking"),
                ("🙄", "Rolling Eyes"),
                ("🤐", "Hushed"),
                ("🤓", "Nerd"),
                ("🙃", "Upside Down"),
                ("🤒", "Sick"),
                ("🤕", "Hurt"),
                ("🤑", "Money"),
    # DULL      ("🏻", "Emoji Modifier Fitzpatrick Type-1-2"),
    # DULL      ("🏼", "Emoji Modifier Fitzpatrick Type-3"),
    # DULL      ("🏽", "Emoji Modifier Fitzpatrick Type-4"),
    # DULL      ("🏾", "Emoji Modifier Fitzpatrick Type-5"),
    # DULL      ("🏿", "Emoji Modifier Fitzpatrick Type-6"),
                ("🤘", "Rock On"),
                ("📿", "Prayer Beads"),
                ("🤖", "Robot"),
                ("🦁", "Lion"),
                ("🦄", "Unicorn"),
    # DULL      ("🦃", "Turkey"),
                ("🦀", "Crab"),
                ("🦂", "Scorpion"),
                ("🧀", "Cheese"),
                ("🌭", "Hot Dog"),
                ("🌮", "Taco"),
                ("🌯", "Burrito"),
                ("🍿", "Popcorn"),
                ("🍾", "Popping Cork"),
    # DULL      ("🏺", "Amphora"),
    # DULL      ("🛐", "Place of Worship"),
    # OFFENSIVE ("🕋", "Kaaba"),
    # OFFENSIVE ("🕌", "Mosque"),
    # OFFENSIVE ("🕍", "Synagogue"),
    # OFFENSIVE ("🕎", "Menorah With Nine Branches"),
                ("🏏", "Cricket"),
                ("🏐", "Volleyball"),
    # 2 SIMILAR ("🏑", "Field Hockey Stick and Ball"),
    # 2 SIMILAR ("🏒", "Ice Hockey Stick and Puck"),
                ("🏓", "Table Tennis"),
    # 2 SIMILAR ("🏸", "Badminton Racquet and Shuttlecock"),
                ("🏹", "Archer"),
    # ---------------------
    # Unicode Version 9.0
    # ---------------------
                ("🤣", "ROFL Face"),
                ("🤤", "Drooling"),
                ("🤢", "Nauseated"),
                ("🤧", "Sneezing"),
                ("🤠", "Cowboy"),
                ("🤡", "Clown"),
                ("🤥", "Lying"),
                ("🤴", "Prince"),
                ("🤵", "Tuxedo Man"),
                ("🤰", "Pregnant"),
                ("🤶", "Mrs. Claus"),
                ("🤦", "Facepalm"),
                ("🤷", "Shrugging"),
                ("🕺", "Man Dancing"),
                ("🤺", "Fencing"),
                ("🤸", "Cartwheeling"),
                ("🤼", "Wrestling"),
    # DULL      ("🤽", "Person Playing Water Polo"),
    # DULL      ("🤾", "Person Playing Handball"),
                ("🤹", "Juggling"),
                ("🤳", "Selfie"),
                ("🤞", "Fingers Crossed"),
                ("🤙", "Call Me Hand"),
    # 2 SIMILAR ("🤛", "Left-Facing Fist"),
                ("🤜", "Fist Hand"),
    # 2 SIMILAR ("🤚", "Raised Back of Hand"),
                ("🤝", "Handshake"),
                ("🖤", "Black Heart"),
    # 2 SIMILAR ("🦍", "Gorilla"),
                ("🦊", "Fox"),
    # 2 SIMILAR ("🦌", "Deer"),
    # 2 SIMILAR ("🦏", "Rhinoceros"),
                ("🦇", "Bat"),
                ("🦅", "Eagle"),
                ("🦆", "Duck"),
                ("🦉", "Owl"),
                ("🦎", "Lizard"),
                ("🦈", "Shark"),
                ("🦐", "Shrimp"),
                ("🦑", "Squid"),
                ("🦋", "Butterfly"),
    # DULL      ("🥀", "Wilted Flower"),
                ("🥝", "Kiwi Fruit"),
                ("🥑", "Avocado"),
                ("🥔", "Potato"),
                ("🥕", "Carrot"),
                ("🥒", "Cucumber"),
                ("🥜", "Peanuts"),
                ("🥐", "Croissant"),
                ("🥖", "Baguette"),
                ("🥞", "Pancakes"),
    # OFFENSIVE ("🥓", "Bacon"),
    # DULL      ("🥙", "Stuffed Flatbread"),
                ("🥚", "Egg"),
    # DULL      ("🥘", "Shallow Pan of Food"),
                ("🥗", "Green Salad"),
                ("🥛", "Milk Glass"),
    # DULL      ("🥂", "Clinking Glasses"),
                ("🥃", "Tumbler"),
                ("🥄", "Spoon"),
    # DULL      ("🛴", "Kick Scooter"),
    # DULL      ("🛵", "Motor Scooter"),
    # DULL      ("🛑", "Stop Sign"),
                ("🛶", "Canoe"),
    # DULL      ("🥇", "1st Place Medal"),
    # DULL      ("🥈", "2nd Place Medal"),
    # DULL      ("🥉", "3rd Place Medal"),
                ("🥊", "Boxing Glove"),
                ("🥋", "Martial Artist"),
                ("🥅", "Goal Net"),
                ("🥁", "Drum"),
                ("🛒", "Shopping Cart"),
    # ---------------------
    # Unicode Version 10.0 (requires Android 8.0+ / iOS 11.1+)
    # ---------------------
)


EMOJI_CHOICES = [(emoji, emoji) for emoji, description in EMOJI_LIST]

EMOJI_NAMES = dict(EMOJI_LIST)
