# Generated by Django 2.1.2 on 2018-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_remove_league_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuecategory',
            name='rotate',
            field=models.BooleanField(default=False, help_text="Marks this category to prioritise venues in the category to debates based on the teams' previous debate venues.", verbose_name='Use in venue rotation'),
        ),
    ]
