# Generated by Django 2.2.10 on 2020-06-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20191217_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelOptions(
            name='venuecategory',
            options={'verbose_name': 'room category', 'verbose_name_plural': 'room categories'},
        ),
        migrations.AlterModelOptions(
            name='venueconstraint',
            options={'verbose_name': 'room constraint', 'verbose_name_plural': 'room constraints'},
        ),
        migrations.AddField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, help_text='A URL that contains extra information about this venue, e.g. a map or a meeting link (for online tournaments)', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='priority',
            field=models.IntegerField(help_text='Rooms with a higher priority number will be preferred when allocating rooms to debates', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='description',
            field=models.CharField(blank=True, help_text='Description, as the predicate of a sentence, e.g. "has step-free access", "is close to the briefing hall". This description follows "This room" when shown in tooltips, e.g., "This room is close to the briefing hall.".', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='display_in_public_tooltip',
            field=models.BooleanField(default=False, help_text='Displays the description in the tooltip for the room on public pages. The description, if not blank, will always show on admin pages.', verbose_name='display in public tooltip'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='display_in_venue_name',
            field=models.CharField(choices=[('-', "Don't display in room name"), ('P', 'Display as prefix'), ('S', 'Display as suffix')], default='-', help_text='Prefix: "Purple – G05", Suffix: "G05 – Purple"', max_length=1, verbose_name='display in room name'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='name',
            field=models.CharField(help_text='Name of category, e.g., "Purple", "Step-free access", "Close to tab room". This name is shown when the category is prefixed or suffixed to a room name in the draw, e.g., "Purple – G05".', max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='venues',
            field=models.ManyToManyField(blank=True, to='venues.Venue', verbose_name='rooms'),
        ),
    ]
