# Generated by Django 3.0.7 on 2020-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_auto_20200608_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, help_text='A URL that contains extra information about this room, e.g. a map or a meeting link (for online tournaments)', verbose_name='URL'),
        ),
    ]
