# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('venues', '0008_auto_20160621_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('subject_id', models.PositiveIntegerField()),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('venue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueGroup')),
            ],
        ),
    ]
