# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:38
from __future__ import unicode_literals

from django.db import migrations


def convert_to_contenttype_model(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    VenueConstraint = apps.get_model("venues", "VenueConstraint")

    TeamVenueConstraint = apps.get_model("venues", "TeamVenueConstraint")
    Team = apps.get_model("participants", "Team")
    for vc in TeamVenueConstraint.objects.all():
        VenueConstraint.objects.create(
            subject_content_type=ContentType.objects.get_for_model(Team),
            subject_id=vc.team_id,
            venue_group=vc.venue_group, priority=vc.priority)

    AdjudicatorVenueConstraint = apps.get_model("venues", "AdjudicatorVenueConstraint")
    Adjudicator = apps.get_model("participants", "Adjudicator")
    for vc in AdjudicatorVenueConstraint.objects.all():
        VenueConstraint.objects.create(
            subject_content_type=ContentType.objects.get_for_model(Adjudicator),
            subject_id=vc.adjudicator_id,
            venue_group=vc.venue_group, priority=vc.priority)

    InstitutionVenueConstraint = apps.get_model("venues", "InstitutionVenueConstraint")
    Institution = apps.get_model("participants", "Institution")
    for vc in InstitutionVenueConstraint.objects.all():
        VenueConstraint.objects.create(
            subject_content_type=ContentType.objects.get_for_model(Institution),
            subject_id=vc.institution_id,
            venue_group=vc.venue_group, priority=vc.priority)

    DivisionVenueConstraint = apps.get_model("venues", "DivisionVenueConstraint")
    Division = apps.get_model("divisions", "Division")
    for vc in DivisionVenueConstraint.objects.all():
        VenueConstraint.objects.create(
            subject_content_type=ContentType.objects.get_for_model(Division),
            subject_id=vc.division_id,
            venue_group=vc.venue_group, priority=vc.priority)


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venueconstraint'),
    ]

    operations = [
        migrations.RunPython(convert_to_contenttype_model, reverse_code=migrations.RunPython.noop)
    ]
