# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_convert_venueconstraint_to_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjudicatorvenueconstraint',
            name='adjudicator',
        ),
        migrations.RemoveField(
            model_name='adjudicatorvenueconstraint',
            name='venue_group',
        ),
        migrations.RemoveField(
            model_name='divisionvenueconstraint',
            name='division',
        ),
        migrations.RemoveField(
            model_name='divisionvenueconstraint',
            name='venue_group',
        ),
        migrations.RemoveField(
            model_name='institutionvenueconstraint',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionvenueconstraint',
            name='venue_group',
        ),
        migrations.RemoveField(
            model_name='teamvenueconstraint',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamvenueconstraint',
            name='venue_group',
        ),
        migrations.DeleteModel(
            name='AdjudicatorVenueConstraint',
        ),
        migrations.DeleteModel(
            name='DivisionVenueConstraint',
        ),
        migrations.DeleteModel(
            name='InstitutionVenueConstraint',
        ),
        migrations.DeleteModel(
            name='TeamVenueConstraint',
        ),
    ]
