# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_delete_old_venue_constraint_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.VenueGroup'),
        ),
    ]
