# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 16:39
# This migration is not reversible, because it involves removing a non-nullable
# field, and this can't be given a default, because we would need to create
# venue groups which are not guaranteed to be disjoint.
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_venue_constraint_categories(apps, schema_editor):
    """Creates VenueConstraintCategories containing the same venues as existing
    VenueGroups, but only for those venue groups that are used in at least one
    constraint."""
    VenueGroup = apps.get_model("venues", "VenueGroup")
    VenueConstraintCategory = apps.get_model("venues", "VenueConstraintCategory")
    VenueConstraint = apps.get_model("venues", "VenueConstraint")

    mapping = {} # groups to categories

    for constraint in VenueConstraint.objects.all():

        # create category if it doesn't already exist
        if constraint.venue_group_id not in mapping:
            group = constraint.venue_group
            category = VenueConstraintCategory(name=group.name)
            category.save()
            category.venues.set(group.venue_set.all())
            category.save()
            mapping[constraint.venue_group_id] = category.id

        # assign constraint category
        constraint.category_id = mapping[constraint.venue_group_id]
        constraint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20160914_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueConstraintCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('venues', models.ManyToManyField(to='venues.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='venueconstraint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.VenueConstraintCategory'),
        ),
        migrations.RunPython(
            create_venue_constraint_categories
        ),
        migrations.RemoveField( # this step is not reversible
            model_name='venueconstraint',
            name='venue_group',
        ),
        migrations.AlterField( # make not nullable
            model_name='venueconstraint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueConstraintCategory'),
        ),
    ]
