# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_change_venuegroup_to_venueconstraintcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueconstraintcategory',
            options={'verbose_name_plural': 'venue constraint categories'},
        ),
    ]
