# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_auto_20170121_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuegroup',
            name='team_capacity',
        ),
    ]
