# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_remove_venuegroup_team_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of category, e.g., "Purple", "Step-free access", "Close to tab room". This name is shown when the category is prefixed or suffixed to a venue name in the draw, e.g., "Purple – G05".', max_length=80, verbose_name='name')),
                ('description', models.CharField(blank=True, help_text='Description, as the predicate of a sentence, e.g. "has step-free access", "is close to the briefing hall". This description follows "This venue" when shown in tooltips, e.g., "This venue is close to the briefing hall.".', max_length=200, verbose_name='description')),
                ('display_in_venue_name', models.CharField(choices=[('-', "Don't display in venue name"), ('P', 'Display as prefix'), ('S', 'Display as suffix')], help_text='Prefix: "Purple – G05", Suffix: "G05 – Purple"', max_length=1, verbose_name='display in venue name')),
                ('display_in_public_tooltip', models.BooleanField(help_text='Displays the description in the tooltip for the venue on public pages. The description, if not blank, will always show on admin pages.', verbose_name='display in public tooltip')),
                ('venues', models.ManyToManyField(to='venues.Venue', verbose_name='venues')),
            ],
            options={
                'verbose_name': 'venue category',
                'verbose_name_plural': 'venue categories',
            },
        ),
    ]
