# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def convert_venueconstraintcategory_to_venuecategory(apps, schema_editor):
    """Creates a VenueCategory for each VenueConstraintCategory.
    VenueCategory instances derived from VenueConstraintCategory will have
    "display in venue name" set to "none", and "display in public tooltip" set
    to False."""

    VenueConstraintCategory = apps.get_model("venues", "VenueConstraintCategory")
    VenueConstraint = apps.get_model("venues", "VenueConstraint")
    VenueCategory = apps.get_model("venues", "VenueCategory")

    mapping = {} # old VenueConstraintCategory to new VenueCategory

    for constraint in VenueConstraint.objects.all():

        # create category if it doesn't already exist
        if constraint.old_category_id not in mapping:
            old_category = constraint.old_category

            new_category = VenueCategory()
            new_category.name = old_category.name
            new_category.description = old_category.name
            new_category.display_in_venue_name = '-'
            new_category.display_in_public_tooltip = False
            new_category.save()
            new_category.venues.set(old_category.venues.all())
            new_category.save()

            mapping[constraint.old_category_id] = new_category.id

        constraint.category_id = mapping[constraint.old_category_id]
        constraint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_convert_venuegroup_to_venuecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueconstraint',
            old_name='category',
            new_name='old_category',
        ),
        migrations.AddField(
            model_name='venueconstraint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venues.VenueCategory'),
        ),
        migrations.RunPython(
            convert_venueconstraintcategory_to_venuecategory,
        ),
        migrations.RemoveField( # this step is not reversible
            model_name='venueconstraint',
            name='old_category',
        ),
        migrations.AlterField( # make not nullable
            model_name='venueconstraint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.VenueCategory'),
        )
    ]
