# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_convert_venueconstraintcategory_to_venuecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='display_in_public_tooltip',
            field=models.BooleanField(default=False, help_text='Displays the description in the tooltip for the venue on public pages. The description, if not blank, will always show on admin pages.', verbose_name='display in public tooltip'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='display_in_venue_name',
            field=models.CharField(choices=[('-', "Don't display in venue name"), ('P', 'Display as prefix'), ('S', 'Display as suffix')], default='-', help_text='Prefix: "Purple – G05", Suffix: "G05 – Purple"', max_length=1, verbose_name='display in venue name'),
        ),
        migrations.AlterIndexTogether(
            name='venue',
            index_together=set([('name',)]),
        ),
    ]
