# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_auto_20170621_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuecategory',
            name='venues',
            field=models.ManyToManyField(blank=True, to='venues.Venue', verbose_name='venues'),
        ),
    ]
