# Generated by Django 5.0.6 on 2024-11-05 21:01

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adjfeedback", "0017_rename_question_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Question",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "seq",
                            models.IntegerField(
                                help_text="The order in which questions are displayed",
                                verbose_name="sequence number",
                            ),
                        ),
                        (
                            "text",
                            models.CharField(
                                help_text='The question displayed to participants, e.g., "Did you agree with the decision?"',
                                max_length=255,
                                verbose_name="text",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(
                                help_text='A short name for the question, e.g., "Agree with decision"',
                                max_length=30,
                                verbose_name="name",
                            ),
                        ),
                        (
                            "answer_type",
                            models.CharField(
                                choices=[
                                    ("bc", "checkbox"),
                                    ("bs", "yes/no (dropdown)"),
                                    ("i", "integer (textbox)"),
                                    ("is", "integer scale"),
                                    ("f", "float"),
                                    ("t", "text"),
                                    ("tl", "long text"),
                                    ("ss", "select one"),
                                    ("ms", "select multiple"),
                                ],
                                max_length=2,
                                verbose_name="answer type",
                            ),
                        ),
                        (
                            "required",
                            models.BooleanField(
                                default=True,
                                help_text="Whether participants are required to fill out this field",
                                verbose_name="required",
                            ),
                        ),
                        (
                            "min_value",
                            models.FloatField(
                                blank=True,
                                help_text="Minimum allowed value for numeric fields (ignored for text or boolean fields)",
                                null=True,
                                verbose_name="minimum value",
                            ),
                        ),
                        (
                            "max_value",
                            models.FloatField(
                                blank=True,
                                help_text="Maximum allowed value for numeric fields (ignored for text or boolean fields)",
                                null=True,
                                verbose_name="maximum value",
                            ),
                        ),
                        (
                            "choices",
                            django_better_admin_arrayfield.models.fields.ArrayField(
                                base_field=models.TextField(),
                                blank=True,
                                default=list,
                                help_text="Permissible choices for select one/multiple fields (ignored for other fields)",
                                size=None,
                                verbose_name="choices",
                            ),
                        ),
                        (
                            "for_content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="for content type",
                            ),
                        ),
                        (
                            "tournament",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="tournaments.tournament",
                                verbose_name="tournament",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "question",
                        "verbose_name_plural": "questions",
                    },
                ),
                migrations.CreateModel(
                    name="ManyAnswer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                        (
                            "answer",
                            django_better_admin_arrayfield.models.fields.ArrayField(
                                base_field=models.TextField(), size=None
                            ),
                        ),
                        (
                            "content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="content type",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="registration.question",
                                verbose_name="question",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "multiple select answer",
                        "verbose_name_plural": "multiple select answers",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="IntegerAnswer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                        ("answer", models.IntegerField(verbose_name="answer")),
                        (
                            "content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="content type",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="registration.question",
                                verbose_name="question",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "integer answer",
                        "verbose_name_plural": "integer answers",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="FloatAnswer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                        ("answer", models.FloatField(verbose_name="answer")),
                        (
                            "content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="content type",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="registration.question",
                                verbose_name="question",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "float answer",
                        "verbose_name_plural": "float answers",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="BooleanAnswer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                        ("answer", models.BooleanField(verbose_name="answer")),
                        (
                            "content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="content type",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="registration.question",
                                verbose_name="question",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "boolean answer",
                        "verbose_name_plural": "boolean answers",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="StringAnswer",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                        ("answer", models.TextField(verbose_name="answer")),
                        (
                            "content_type",
                            models.ForeignKey(
                                limit_choices_to=models.Q(
                                    models.Q(
                                        ("app_label", "adjfeedback"),
                                        ("model", "adjudicatorfeedback"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"),
                                        ("model", "tournamentinstitution"),
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "speaker")
                                    ),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "adjudicator")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "coach")),
                                    models.Q(
                                        ("app_label", "participants"), ("model", "person")
                                    ),
                                    models.Q(("app_label", "participants"), ("model", "team")),
                                    _connector="OR",
                                ),
                                on_delete=django.db.models.deletion.CASCADE,
                                to="contenttypes.contenttype",
                                verbose_name="content type",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="registration.question",
                                verbose_name="question",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "string answer",
                        "verbose_name_plural": "string answers",
                        "abstract": False,
                    },
                ),
                migrations.AddConstraint(
                    model_name="manyanswer",
                    constraint=utils.models.UniqueConstraint(
                        fields=("question", "content_type", "object_id"),
                        name="registr_manyanswer_question__content_type__object_id_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="integeranswer",
                    constraint=utils.models.UniqueConstraint(
                        fields=("question", "content_type", "object_id"),
                        name="registr_integeranswer_question__content_type__object_id_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="floatanswer",
                    constraint=utils.models.UniqueConstraint(
                        fields=("question", "content_type", "object_id"),
                        name="registr_floatanswer_question__content_type__object_id_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="booleananswer",
                    constraint=utils.models.UniqueConstraint(
                        fields=("question", "content_type", "object_id"),
                        name="registr_booleananswer_question__content_type__object_id_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="stringanswer",
                    constraint=utils.models.UniqueConstraint(
                        fields=("question", "content_type", "object_id"),
                        name="registr_stringanswer_question__content_type__object_id_uniq",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    f"ALTER INDEX adjfeed_{table}_question__content_type__object_id_uniq RENAME TO registr_{table}_question__content_type__object_id_uniq;",
                    f"ALTER INDEX registr_{table}_question__content_type__object_id_uniq RENAME TO adjfeed_{table}_question__content_type__object_id_uniq;",
                )
                for table in ('booleananswer', 'floatanswer', 'integeranswer', 'manyanswer', 'stringanswer')
            ],
            state_operations=[]
        ),
    ]
