# Generated by Django 5.2.7 on 2026-01-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('bc', 'checkbox'), ('bs', 'yes/no (dropdown)'), ('i', 'integer (textbox)'), ('is', 'integer scale'), ('f', 'float'), ('t', 'text'), ('tl', 'long text'), ('ss', 'select one'), ('ms', 'select multiple'), ('dt', 'date + time')], max_length=2, verbose_name='answer type'),
        ),
    ]
