# Generated by Django 5.2.2 on 2025-09-30 14:50

import django.db.models.deletion
import registration.models
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('participants', '0028_alter_tournamentinstitution_adjudicators_requested_and_more'),
        ('registration', '0002_invitation_and_more'),
        ('tournaments', '0013_scheduleevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('bc', 'checkbox'), ('bs', 'yes/no (dropdown)'), ('i', 'integer (textbox)'), ('is', 'integer scale'), ('f', 'float'), ('t', 'text'), ('tl', 'long text'), ('ss', 'select one'), ('ms', 'select multiple'), ('dt', 'date + time')], max_length=2, verbose_name='answer type'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('submitter_type', models.CharField(choices=[('T', 'Tab room'), ('P', 'Public'), ('A', 'Automation')], max_length=1, verbose_name='submitter type')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('private_url', models.BooleanField(default=False, verbose_name='from private URL')),
                ('confirm_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='confirm timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('amount', registration.models.ArbitraryDecimalField()),
                ('currency', models.CharField(choices=[('cad', 'Canadian Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('usd', 'United States Dollar')])),
                ('note', models.TextField(blank=True)),
                ('confirmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='confirmer')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution')),
                ('participant_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_participant_submitted', to='participants.person', verbose_name='from participant')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.person')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', registration.models.ArbitraryDecimalField()),
                ('currency', models.CharField(choices=[('cad', 'Canadian Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('usd', 'United States Dollar')])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('from_registration', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('v', 'Void'), ('o', 'Open'), ('p', 'Paid')], max_length=1)),
                ('amount_paid', registration.models.ArbitraryDecimalField()),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', registration.models.ArbitraryDecimalField()),
                ('currency', models.CharField(choices=[('cad', 'Canadian Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('usd', 'United States Dollar')])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.invoice')),
            ],
            options={
                'verbose_name': 'invoice payment',
                'verbose_name_plural': 'invoice payments',
            },
        ),
        migrations.CreateModel(
            name='LineDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.discount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('submitter_type', models.CharField(choices=[('T', 'Tab room'), ('P', 'Public'), ('A', 'Automation')], max_length=1, verbose_name='submitter type')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('private_url', models.BooleanField(default=False, verbose_name='from private URL')),
                ('confirm_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='confirm timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('reference', models.CharField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', registration.models.ArbitraryDecimalField()),
                ('currency', models.CharField(choices=[('cad', 'Canadian Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('usd', 'United States Dollar')])),
                ('method', models.CharField(choices=[('c', 'cash'), ('w', 'wire'), ('', 'other'), ('s', 'Stripe')], max_length=1)),
                ('status', models.CharField(choices=[('c', 'Completed'), ('r', 'Refunded'), ('f', 'Failed'), ('h', 'On hold'), ('e', 'Expired')], max_length=1)),
                ('confirmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='confirmer')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution')),
                ('invoices', models.ManyToManyField(through='registration.InvoicePayment', to='registration.invoice')),
                ('participant_submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_participant_submitted', to='participants.person', verbose_name='from participant')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.person')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.payment'),
        ),
        migrations.CreateModel(
            name='PaymentScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('percentage_required', models.FloatField(help_text='The cumulative percentage of the invoice to be paid by the time', verbose_name='percentage required')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'payment schedule event',
                'verbose_name_plural': 'payment schedule events',
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('p', 'participant registration'), ('a', 'adjudicator registration'), ('t', 'team registration'), ('s', 'speaker registration'), ('o', 'observer registration'), ('m', 'missing adjudicator fee'), ('', 'custom fee')], help_text='If an option is selected, the item will be auto-populated in invoices where applicable', max_length=1, null=True, verbose_name='item type')),
                ('name', models.CharField(blank=True, help_text="Optional; overrides the default name from the item's type", max_length=100, verbose_name='name')),
                ('amount', registration.models.ArbitraryDecimalField(verbose_name='amount')),
                ('currency', models.CharField(choices=[('cad', 'Canadian Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound'), ('usd', 'United States Dollar')], max_length=3, verbose_name='currency')),
                ('stripe_product_id', models.CharField(blank=True, null=True, unique=True, verbose_name='Stripe product ID')),
                ('stripe_price_id', models.CharField(blank=True, null=True, unique=True, verbose_name='Stripe price ID')),
                ('active', models.BooleanField(blank=True, default=True, help_text='Should the item be applied to future invoices?', verbose_name='active')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.institution')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.invoice')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.team')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.priceitem')),
            ],
        ),
        migrations.CreateModel(
            name='SlotTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('for_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'adjfeedback'), ('model', 'adjudicatorfeedback')), models.Q(('app_label', 'participants'), ('model', 'tournamentinstitution')), models.Q(('app_label', 'participants'), ('model', 'speaker')), models.Q(('app_label', 'participants'), ('model', 'adjudicator')), models.Q(('app_label', 'participants'), ('model', 'coach')), models.Q(('app_label', 'participants'), ('model', 'person')), models.Q(('app_label', 'participants'), ('model', 'team')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='for content type')),
                ('from_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_institution_set', to='participants.institution', verbose_name='from institution')),
                ('to_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_institution_set', to='participants.institution', verbose_name='to institution')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'slot transfer',
                'verbose_name_plural': 'slot transfers',
            },
        ),
        migrations.CreateModel(
            name='PaymentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('s', 'Stripe'), ('p', 'PayPal')], max_length=1)),
                ('external_id', models.CharField()),
                ('status', models.CharField(choices=[('c', 'connected'), ('d', 'disconnected'), ('p', 'pending')], max_length=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'payment connection',
                'verbose_name_plural': 'payment connections',
                'constraints': [utils.models.UniqueConstraint(fields=('tournament', 'platform'), name='registr_paymentconnection_tournament__platform_uniq')],
            },
        ),
    ]
