# Generated by Django 5.2.8 on 2026-02-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0030_adjudicator_registration_status_and_more'),
        ('registration', '0002_invitation_and_more'),
        ('tournaments', '0015_alter_round_draw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('bc', 'checkbox'), ('bs', 'yes/no (dropdown)'), ('i', 'integer (textbox)'), ('is', 'integer scale'), ('f', 'float'), ('t', 'text'), ('tl', 'long text'), ('ss', 'select one'), ('ms', 'select multiple'), ('dt', 'date + time')], max_length=2, verbose_name='answer type'),
        ),
        migrations.CreateModel(
            name='SlotTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_transferred', models.PositiveIntegerField(default=0, verbose_name='team slots transferred')),
                ('adjudicators_transferred', models.PositiveIntegerField(default=0, verbose_name='adjudicator slots transferred')),
                ('receiving_institution_name', models.CharField(blank=True, max_length=100, verbose_name='receiving institution name')),
                ('receiving_institution_email', models.EmailField(blank=True, max_length=254, verbose_name='receiving institution contact email')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], db_index=True, default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receiving_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_transfer_target_set', to='participants.tournamentinstitution', verbose_name='receiving institution')),
                ('source_tournament_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_transfer_source_set', to='participants.tournamentinstitution', verbose_name='source institution')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'slot transfer request',
                'verbose_name_plural': 'slot transfer requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='slot_transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.slottransferrequest', verbose_name='slot transfer request'),
        ),
    ]
