# Generated by Django 2.0.2 on 2018-03-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0003_auto_20180305_1543'),
        ('actionlog', '0003_auto_20180304_2218'),
    ]

    operations = [
    ]
