# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0005_auto_20160109_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlogentry',
            options={'verbose_name_plural': 'action log entries'},
        ),
    ]
