# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0013_convert_content_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlogentry',
            name='adjudicator',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='adjudicator_feedback',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='adjudicator_test_score_history',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='ballot_submission',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='break_category',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='debate',
        ),
        migrations.RemoveField(
            model_name='actionlogentry',
            name='motion',
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='type',
            field=models.CharField(choices=[('ba.disc', 'Discarded ballot set'), ('ba.ckin', 'Checked in ballot set'), ('ba.crea', 'Created ballot set'), ('ba.edit', 'Edited ballot set'), ('ba.conf', 'Confirmed ballot set'), ('ba.subm', 'Submitted ballot set from the public form'), ('fb.subm', 'Submitted feedback from the public form'), ('fb.save', 'Saved feedback'), ('ts.edit', 'Edited adjudicator test score'), ('aj.note', 'Set adjudicator note'), ('aa.save', 'Saved adjudicator allocation'), ('aa.auto', 'Auto-allocated adjudicators'), ('ve.save', 'Saved venues'), ('ve.auto', 'Auto-allocated venues'), ('dr.crea', 'Created draw'), ('dr.conf', 'Confirmed draw'), ('dr.rege', 'Regenerated draw'), ('dr.rele', 'Released draw'), ('dr.unre', 'Unreleased draw'), ('dv.save', 'Saved divisions'), ('mo.edit', 'Added/edited motion'), ('mo.rele', 'Released motions'), ('mo.unre', 'Unreleased motions'), ('db.im.edit', 'Edited debate importance'), ('br.aj.set', 'Changed adjudicator breaking status'), ('br.el.edit', 'Edited break eligibility'), ('br.gene', 'Generated the team break for all categories'), ('br.upda', 'Edited breaking team remarks and updated all team breaks'), ('br.upd1', 'Edited breaking team remarks and updated this team break'), ('br.rm.edit', 'Edited breaking team remarks'), ('rd.st.set', 'Set start time'), ('av.tm.save', 'Edited teams availability'), ('av.aj.save', 'Edited adjudicators availability'), ('av.ve.save', 'Edited venue availability'), ('op.edit', 'Edited tournament options')], max_length=10),
        ),
    ]
