# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0014_remove_old_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogentry',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Round'),
        ),
        migrations.AlterField(
            model_name='actionlogentry',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Tournament'),
        ),
    ]
