# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0005_auto_20160228_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakcategory',
            name='rule',
            field=models.CharField(choices=[('s', 'Standard'), ('a', 'AIDA pre-2015'), ('b', 'AIDA 2016')], default='s', max_length=1),
        ),
    ]
