# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to be displayed, e.g., "ESL"', max_length=50)),
                ('slug', models.SlugField(help_text='Slug for URLs, e.g., "esl"')),
                ('seq', models.IntegerField(help_text='The order in which the categories are displayed')),
                ('break_size', models.IntegerField(help_text='Number of breaking teams in this category')),
                ('is_general', models.BooleanField(help_text='True if most teams eligible for this category, e.g. Open, False otherwise')),
                ('institution_cap', models.IntegerField(blank=True, help_text='Maximum number of teams from a single institution in this category; leave blank if not applicable', null=True)),
                ('priority', models.IntegerField(help_text='If a team breaks in multiple categories, lower priority numbers take precedence; teams can break into multiple categories if and only if they all have the same priority')),
            ],
            options={
                'verbose_name_plural': 'break categories',
                'ordering': ['tournament', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='BreakingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('break_rank', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, choices=[('C', 'Capped'), ('I', 'Ineligible'), ('D', 'Different break'), ('d', 'Disqualified'), ('t', 'Lost coin toss'), ('w', 'Withdrawn')], help_text="Used to explain why an otherwise-qualified team didn't break", max_length=1, null=True)),
                ('break_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakqual.BreakCategory')),
            ],
        ),
    ]
