# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('breakqual', '0002_auto_20160103_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakcategory',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='breakingteam',
            unique_together=set([('break_category', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='breakcategory',
            unique_together=set([('tournament', 'slug'), ('tournament', 'seq')]),
        ),
        migrations.AlterIndexTogether(
            name='breakcategory',
            index_together=set([('tournament', 'seq')]),
        ),
    ]
