# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0003_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakcategory',
            options={'ordering': ['tournament', 'seq'], 'verbose_name': '🎉 Break Category', 'verbose_name_plural': '🎉 Break Categories'},
        ),
        migrations.AlterModelOptions(
            name='breakingteam',
            options={'verbose_name': '👑 Breaking Team'},
        ),
    ]
