# Generated by Django 4.1.7 on 2024-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0005_remove_league_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakcategory',
            name='is_general',
            field=models.BooleanField(help_text='Are teams eligible for this break by default', verbose_name='is general'),
        ),
    ]
