# Generated by Django 5.0.4 on 2024-09-06 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0006_alter_breakcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakcategory',
            name='reserve_size',
            field=models.IntegerField(default=0, help_text='Number of reserve teams in this category.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reserve size'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='remark',
            field=models.CharField(blank=True, choices=[('C', 'Capped'), ('I', 'Ineligible'), ('D', 'Different break'), ('d', 'Disqualified'), ('t', 'Lost coin toss'), ('w', 'Withdrawn'), ('R', 'Reserve')], help_text="Used to explain why an otherwise-qualified team didn't break", max_length=1, null=True, verbose_name='remark'),
        ),
    ]
