# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0006_breakcategory_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakcategory',
            name='institution_cap',
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='priority',
            field=models.IntegerField(help_text='If a team breaks in multiple categories, higher priority numbers take precedence; teams can break into multiple categories if and only if they all have the same priority'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='rule',
            field=models.CharField(choices=[('standard', 'Standard'), ('aida-pre2015', 'AIDA Pre-2015'), ('aida-2016-easters', 'AIDA 2016 (Easters)'), ('aida-2016-australs', 'AIDA 2016 (Australs)')], default='standard', help_text='Rule for how the break is calculated (most tournaments should use "Standard")', max_length=25),
        ),
    ]
