# Generated by Django 5.0.4 on 2024-09-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0007_breakcategory_reserve_size_alter_breakingteam_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakcategory',
            name='reserve_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of reserve teams in this category.', verbose_name='Reserve size'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='remark',
            field=models.CharField(blank=True, choices=[('C', 'Capped'), ('I', 'Ineligible'), ('D', 'Different break'), ('d', 'Disqualified'), ('t', 'Lost coin toss'), ('w', 'Withdrawn'), ('R', 'Reserve'), ('A', 'Absent')], help_text="Used to explain why an otherwise-qualified team didn't break", max_length=1, null=True, verbose_name='remark'),
        ),
    ]
