# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0012_convert_aida_pre2015_to_1996'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakcategory',
            options={'ordering': ['tournament', 'seq'], 'verbose_name': 'break category', 'verbose_name_plural': 'break categories'},
        ),
        migrations.AlterModelOptions(
            name='breakingteam',
            options={'verbose_name': 'breaking team', 'verbose_name_plural': 'breaking teams'},
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='break_size',
            field=models.IntegerField(help_text='Number of breaking teams in this category', validators=[django.core.validators.MinValueValidator(2)], verbose_name='break size'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='breaking_teams',
            field=models.ManyToManyField(through='breakqual.BreakingTeam', to='participants.Team', verbose_name='breaking teams'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='is_general',
            field=models.BooleanField(help_text='True if most teams eligible for this category, e.g. Open, False otherwise', verbose_name='is general'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='name',
            field=models.CharField(help_text='Name to be displayed, e.g., "ESL"', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='priority',
            field=models.IntegerField(help_text='If a team breaks in multiple categories, higher priority numbers take precedence; teams can break into multiple categories if and only if they all have the same priority', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='rule',
            field=models.CharField(choices=[('standard', 'Standard'), ('aida-1996', 'AIDA 1996'), ('aida-2016-easters', 'AIDA 2016 (Easters)'), ('aida-2016-australs', 'AIDA 2016 (Australs)'), ('wadl-div-first', 'WADL division winners first'), ('wadl-div-guaranteed', 'WADL division winners guaranteed')], default='standard', help_text='Rule for how the break is calculated (most tournaments should use "Standard")', max_length=25, verbose_name='rule'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='seq',
            field=models.IntegerField(help_text='The order in which the categories are displayed', verbose_name='sequence number'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='slug',
            field=models.SlugField(help_text='Slug for URLs, e.g., "esl"', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='breakcategory',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='tournament'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='break_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakqual.BreakCategory', verbose_name='break category'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='break_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='break rank'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='remark',
            field=models.CharField(blank=True, choices=[('C', 'Capped'), ('I', 'Ineligible'), ('D', 'Different break'), ('d', 'Disqualified'), ('t', 'Lost coin toss'), ('w', 'Withdrawn')], help_text="Used to explain why an otherwise-qualified team didn't break", max_length=1, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='breakingteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team', verbose_name='team'),
        ),
    ]
