# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('participants', '0001_initial'),
        ('draw', '0002_teamvenuepreference_team'),
        ('adjallocation', '0002_auto_20160103_1927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adjfeedback', '0002_adjudicatortestscorehistory_adjudicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicatortestscorehistory',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Round'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackstringanswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackstringanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackquestion',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackintegeranswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackintegeranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackfloatanswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackfloatanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackbooleananswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedbackbooleananswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjfeedback_adjudicatorfeedback_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='source_adjudicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjallocation.DebateAdjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='source_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draw.DebateTeam'),
        ),
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjfeedback_adjudicatorfeedback_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedbackstringanswer',
            unique_together=set([('question', 'feedback')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedbackquestion',
            unique_together=set([('tournament', 'reference'), ('tournament', 'seq')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedbackintegeranswer',
            unique_together=set([('question', 'feedback')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedbackfloatanswer',
            unique_together=set([('question', 'feedback')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedbackbooleananswer',
            unique_together=set([('question', 'feedback')]),
        ),
        migrations.AlterUniqueTogether(
            name='adjudicatorfeedback',
            unique_together=set([('adjudicator', 'source_adjudicator', 'source_team', 'version')]),
        ),
    ]
