# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0003_auto_20160103_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicatorfeedback',
            options={'verbose_name': '🙅 Adj Feedback'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatorfeedbackquestion',
            options={'verbose_name': '❓ Adj Feedback Question'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatortestscorehistory',
            options={'verbose_name': '🚨 Adj Test Score History', 'verbose_name_plural': '🚨 Adj Test Score Histories'},
        ),
    ]
