# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0005_auto_20160228_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='chair_on_panellist',
            field=models.BooleanField(help_text='Despite the name, applies to all adjudicator-on-adjudicator feedback'),
        ),
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='panellist_on_chair',
            field=models.BooleanField(help_text='Not currently used, reserved for future use'),
        ),
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='panellist_on_panellist',
            field=models.BooleanField(help_text='Not currently used, reserved for future use'),
        ),
    ]
