# Generated by Django 2.2.9 on 2020-06-13 18:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def populate_answers(apps, schema_editor):
    string_answers = apps.get_model('adjfeedback', 'adjudicatorfeedbackstringanswer')
    many_answers = apps.get_model('adjfeedback', 'AdjudicatorFeedbackManyAnswer')
    for sa in string_answers.objects.filter(question__answer_type='ms'):  # Multiple select
        many_answers.objects.create(answer=sa.answer.split('//'), feedback_id=sa.feedback_id, question_id=sa.question_id)
    string_answers.objects.filter(question__answer_type='ms').delete()


def depopulate_answers(apps, schema_editor):
    string_answers = apps.get_model('adjfeedback', 'adjudicatorfeedbackstringanswer')
    many_answers = apps.get_model('adjfeedback', 'AdjudicatorFeedbackManyAnswer')
    for ma in many_answers.objects.all():
        string_answers.objects.create(answer='//'.join(ma.answer), feedback_id=ma.feedback_id, question_id=ma.question_id)
    many_answers.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0006_auto_20191109_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicatorfeedbackquestion',
            name='choices_temp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text="Permissible choices for select one/multiple fields (ignored for other fields)", size=None, verbose_name='choices', default=list),
        ),
        migrations.RunSQL(
            sql="UPDATE adjfeedback_adjudicatorfeedbackquestion SET choices_temp=string_to_array(choices, '//');",
            reverse_sql="UPDATE adjfeedback_adjudicatorfeedbackquestion SET choices=array_to_string(choices_temp, '//');",
        ),
        migrations.RemoveField(
            model_name='adjudicatorfeedbackquestion',
            name='choices',
        ),
        migrations.RenameField(
            model_name='adjudicatorfeedbackquestion',
            old_name='choices_temp',
            new_name='choices',
        ),
        migrations.CreateModel(
            name='AdjudicatorFeedbackManyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback', verbose_name='feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'adjudicator feedback multiple select answer',
                'verbose_name_plural': 'adjudicator feedback multiple select answers',
                'abstract': False,
                'unique_together': {('question', 'feedback')},
            },
        ),
        migrations.RunPython(populate_answers, reverse_code=depopulate_answers),
    ]
