# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0006_auto_20160716_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjudicatorfeedbackquestion',
            old_name='chair_on_panellist',
            new_name='from_adj',
        ),
        migrations.RenameField(
            model_name='adjudicatorfeedbackquestion',
            old_name='team_on_orallist',
            new_name='from_team',
        ),
        migrations.RemoveField(
            model_name='adjudicatorfeedbackquestion',
            name='panellist_on_chair',
        ),
        migrations.RemoveField(
            model_name='adjudicatorfeedbackquestion',
            name='panellist_on_panellist',
        ),
    ]
