# Generated by Django 2.2.9 on 2020-06-13 18:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0006_auto_20191109_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicatorfeedbackquestion',
            name='choices_temp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text="Permissible choices for select one/multiple fields (ignored for other fields)", size=None, verbose_name='choices', default=list),
        ),
        migrations.RunSQL(
            sql="UPDATE adjfeedback_adjudicatorfeedbackquestion SET choices_temp=string_to_array(choices, '//');",
            reverse_sql="UPDATE adjfeedback_adjudicatorfeedbackquestion SET choices=array_to_string(choices_temp, '//');",
        ),
        migrations.RemoveField(
            model_name='adjudicatorfeedbackquestion',
            name='choices',
        ),
        migrations.RenameField(
            model_name='adjudicatorfeedbackquestion',
            old_name='choices_temp',
            new_name='choices',
        ),
        migrations.CreateModel(
            name='AdjudicatorFeedbackManyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedback', verbose_name='feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjfeedback.AdjudicatorFeedbackQuestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'adjudicator feedback multiple select answer',
                'verbose_name_plural': 'adjudicator feedback multiple select answers',
                'abstract': False,
                'unique_together': {('question', 'feedback')},
            },
        ),
        migrations.RunSQL(
            sql="INSERT INTO adjfeedback_adjudicatorfeedbackmanyanswer (answer, feedback_id, question_id) SELECT string_to_array(a.answer, '//'), a.feedback_id, q.id FROM adjfeedback_adjudicatorfeedbackstringanswer a INNER JOIN adjfeedback_adjudicatorfeedbackquestion q ON a.question_id=q.id WHERE q.answer_type='ms';",
            reverse_sql="INSERT INTO adjfeedback_adjudicatorfeedbackstringanswer (answer, feedback_id, question_id) SELECT array_to_string(answers, '//'), feedback_id, question_id FROM (SELECT array_agg(answer) answers, feedback_id, question_id) FROM adjfeedback_adjudicatorfeedbackmanyanswer GROUP BY feedback_id, question_id;",
        ),
        migrations.RunSQL(
            sql="DELETE FROM adjfeedback_adjudicatorfeedbackstringanswer WHERE question_id IN (SELECT id FROM adjfeedback_adjudicatorfeedbackquestion WHERE answer_type='ms');",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
