# Generated by Django 2.2.13 on 2020-08-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_auto_20200705_1317'),
        ('adjfeedback', '0008_auto_20200705_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicatorfeedback',
            name='participant_submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjfeedback_adjudicatorfeedback_participant_submitted', to='participants.Person', verbose_name='from participant'),
        ),
    ]
