# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0008_auto_20160726_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='choices',
            field=models.CharField(blank=True, default='', help_text="Permissible choices for select one/multiple fields, separated by '//' (ignored for other fields)", max_length=500),
            preserve_default=False,
        ),
    ]
