# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0009_auto_20160914_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatorfeedbackstringanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
