# Generated by Django 3.1.1 on 2020-09-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0009_adjudicatorfeedback_participant_submitter'),
        ('adjfeedback', '0009_merge_20200904_1639'),
    ]

    operations = [
    ]
