# This migration merges the changes of what were previously:
#  - 0011_auto_20201226_0143.py (Generated by Django 3.1.1 on 2020-12-26 09:43)
# and
#  - 0011_auto_20201226_1713.py.(Generated by Django 3.1.4 on 2020-12-27 01:13)
#
# If you've already applied either migration, you might need to remove those
# migrations from your migration history, and then run `dj migrate` again. Since
# this migration incorporates changes from both of them, and would just
# overwrite those changes, it should be safe to do this, whether you've applied
# zero, one or both of those older migrations.

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0010_merge_20200904_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatorfeedbackmanyanswer',
            name='answer',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='choices',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Permissible choices for select one/multiple fields (ignored for other fields), delimit options with commas', size=None, verbose_name='choices'),
        ),
    ]
