# Generated by Django 3.1.1 on 2020-12-26 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjfeedback', '0010_merge_20200904_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicatorfeedbackquestion',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Permissible choices for select one/multiple fields (ignored for other fields), delimit options with commas', size=None, verbose_name='choices'),
        ),
    ]
