# Generated by Django 4.1.7 on 2023-09-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adjfeedback", "0013_alter_adjudicatorfeedback_confirmer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjudicatorfeedback",
            name="submitter_type",
            field=models.CharField(
                choices=[("T", "Tab room"), ("P", "Public"), ("A", "Automation")],
                max_length=1,
                verbose_name="submitter type",
            ),
        ),
    ]
