# Generated by Django 5.0.6 on 2024-11-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adjfeedback", "0017_rename_question_models"),
        ("adjfeedback", "0018_null_op_registration"),
    ]

    operations = []
