# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjallocation', '0002_auto_20160103_1927'),
        ('tournaments', '0001_initial'),
        ('draw', '0003_auto_20160103_1927'),
        ('venues', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Division'),
        ),
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='team',
            name='venue_preferences',
            field=models.ManyToManyField(related_name='venue_preferences', through='draw.TeamVenuePreference', to='venues.VenueGroup', verbose_name='Venue group preference'),
        ),
        migrations.AddField(
            model_name='region',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('emoji_seq', 'tournament'), ('reference', 'institution', 'tournament')]),
        ),
        migrations.AlterIndexTogether(
            name='team',
            index_together=set([('tournament', 'institution', 'short_reference')]),
        ),
        migrations.AddField(
            model_name='speaker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('name', 'code')]),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='conflicts',
            field=models.ManyToManyField(related_name='adj_adj_conflicts', through='adjallocation.AdjudicatorConflict', to='participants.Team'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='institution_conflicts',
            field=models.ManyToManyField(related_name='adj_inst_conflicts', through='adjallocation.AdjudicatorInstitutionConflict', to='participants.Institution'),
        ),
        migrations.AddField(
            model_name='adjudicator',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
