# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 10:18

# Note: This created a leaf node conflict when it was created; it's now marked
# as having been replaced by 0002_auto_20171201_1130.

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicator',
            options={'verbose_name': 'adjudicator', 'verbose_name_plural': 'adjudicators'},
        ),
    ]
