# Generated by Django 2.0.2 on 2018-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20180307_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code_name',
            field=models.CharField(blank=True, help_text='Name used to obscure institutional identity on public-facing pages', max_length=150, verbose_name='code name'),
        ),
    ]
