# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_auto_20160109_1904'),
        ('venues', '0002_auto_20160109_1834'),
        ('participants', '0003_auto_20160109_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='venue_preferences',
            field=models.ManyToManyField(related_name='institution_venue_preferences', through='draw.InstitutionVenuePreference', to='venues.VenueGroup', verbose_name='Venue group preference'),
        ),
        migrations.AlterField(
            model_name='team',
            name='venue_preferences',
            field=models.ManyToManyField(related_name='team_venue_preferences', through='draw.TeamVenuePreference', to='venues.VenueGroup', verbose_name='Venue group preference'),
        ),
    ]
