# Generated by Django 2.0.5 on 2018-07-17 11:20
# Extended manually to move existing keys to new table

from django.db import migrations, models


def populate_participant_urls(apps, schema_editor):
    Person = apps.get_model("participants", "Person")
    Adjudicator = apps.get_model("participants", "Adjudicator")
    Team = apps.get_model("participants", "Team")

    for team in Team.objects.all():
        speaker = team.speaker_set.first()
        rel = Person.objects.get(pk=speaker.pk)
        rel.url_key_ = team.url_key
        rel.save()

    for adj in Adjudicator.objects.all():
        rel = Person.objects.get(pk=adj.pk)
        rel.url_key_ = adj.url_key
        rel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_welcome_msg'),
        ('participants', '0004_auto_20180420_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url_key_',
            field=models.SlugField(blank=True, max_length=24, null=True, unique=True, verbose_name='URL key'),
        ),
        migrations.RunPython(populate_participant_urls),
        migrations.RemoveField(
            model_name='adjudicator',
            name='url_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='url_key',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='url_key_',
            new_name='url_key',
        ),
    ]
