# Generated by Django 2.0.2 on 2018-03-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20180310_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='barcode_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='checkin_message',
        ),
    ]
