# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20160127_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='emoji_seq',
        ),
    ]
