# Generated by Django 2.1.3 on 2018-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_auto_20180909_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicator',
            name='adj_core',
            field=models.BooleanField(blank=True, default=False, verbose_name='adjudication core'),
        ),
        migrations.AlterField(
            model_name='adjudicator',
            name='independent',
            field=models.BooleanField(blank=True, default=False, verbose_name='independent'),
        ),
    ]
