# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_auto_20160128_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender is displayed in the adjudicator allocation interface, and nowhere else', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='novice',
            field=models.BooleanField(default=False, help_text='Novice status is indicated on the tab, and may have its own Break Category or Top Speakers Tab'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pronoun',
            field=models.CharField(blank=True, help_text='If printing ballots using Tabbycat there is the option to pre-print pronouns', max_length=10, null=True),
        ),
    ]
