# Generated by Django 2.1.8 on 2019-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20190227_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='division',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
    ]
