# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_auto_20160507_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='divisions.Division'),
        ),
    ]
