# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_auto_20160621_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='long_name',
            field=models.CharField(default="Team names aren't set; please finish applying database migrations", help_text='The full name of the team, including institution name. This is autogenerated, so do not edit this yourself.', max_length=200, verbose_name='Long name (autogenerated)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='No short name, please finish migrations', help_text='The name shown in the draw, including institution name. This is autogenerated, so do not edit this yourself.', max_length=50, verbose_name='Short name (autogenerated)'),
            preserve_default=False,
        ),
    ]
