# Generated by Django 3.1.1 on 2020-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_merge_20200904_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(editable=False, help_text='The decoded name shown in the draw, including institution name. (This is autogenerated.)', max_length=56, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_reference',
            field=models.CharField(blank=True, help_text='The decoded name shown in the draw, not including institution name (see "uses institutional prefix" below)', max_length=35, verbose_name='short name/suffix'),
        ),
    ]
