# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0018_auto_20160712_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='reference',
            field=models.CharField(blank=True, help_text='Do not include institution name (see "uses institutional prefix" below)', max_length=150, verbose_name='Full name/suffix'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_reference',
            field=models.CharField(blank=True, help_text='The name shown in the draw. Do not include institution name (see "uses institutional prefix" below)', max_length=35, verbose_name='Short name/suffix'),
        ),
    ]
