# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0019_allow_blank_team_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', help_text='Gender is displayed in the adjudicator allocation interface, and nowhere else', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='pronoun',
            field=models.CharField(blank=True, default='', help_text='If printing ballots using Tabbycat there is the option to pre-print pronouns', max_length=10),
            preserve_default=False,
        ),
    ]
