# Generated by Django 5.0.4 on 2024-05-04 21:38

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0022_rename_team_tournament_institution_short_reference_participant_tournam_160efa_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=utils.models.UniqueConstraint(fields=('name', 'code'), name='partici_institution_name__code_uniq'),
        ),
    ]
