# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0022_auto_20170121_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='tournament',
        ),
    ]
