# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0023_remove_region_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Anonymous persons will have their name and team hidden on public tab releases'),
        ),
    ]
