# Generated by Django 5.0.4 on 2024-09-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0023_alter_unique_together_and_team_emoji'),
        ('tournaments', '0013_scheduleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_requested', models.PositiveIntegerField(verbose_name='Team slots requested')),
                ('teams_allocated', models.PositiveIntegerField(verbose_name='Team slots allocatd')),
                ('adjudicators_requested', models.PositiveIntegerField(verbose_name='Adjudicator slots requested')),
                ('adjudicators_allocated', models.PositiveIntegerField(verbose_name='Adjudicator slots allocated')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.institution', verbose_name='institution')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='tournament')),
            ],
        ),
    ]
