# Generated by Django 5.0.4 on 2024-09-27 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0024_tournamentinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participants.person')),
                ('tournament_institution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='participants.tournamentinstitution', verbose_name='tournament institution')),
            ],
            options={
                'verbose_name': 'coach',
                'verbose_name_plural': 'coaches',
            },
            bases=('participants.person',),
        ),
    ]
