# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0024_person_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Anonymous persons will have their name and team redacted on public tab releases'),
        ),
    ]
