# Generated by Django 5.1.5 on 2025-02-28 02:12

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0025_alter_tournamentinstitution_teams_allocated_coach"),
        ("tournaments", "0013_scheduleevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournamentinstitution",
            options={
                "verbose_name": "tournament institution",
                "verbose_name_plural": "tournament institutions",
            },
        ),
        migrations.AlterField(
            model_name="tournamentinstitution",
            name="teams_allocated",
            field=models.PositiveIntegerField(verbose_name="Team slots allocated"),
        ),
        migrations.AddConstraint(
            model_name="tournamentinstitution",
            constraint=utils.models.UniqueConstraint(
                fields=("tournament", "institution"),
                name="partici_tournamentinstitution_tournament__institution_uniq",
            ),
        ),
    ]
