# Generated by Django 5.1.5 on 2025-03-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0026_alter_tournamentinstitution_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentinstitution",
            name="adjudicators_allocated",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Adjudicator slots allocated"
            ),
        ),
        migrations.AlterField(
            model_name="tournamentinstitution",
            name="teams_allocated",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Team slots allocated"
            ),
        ),
    ]
