# Generated by Django 5.0.6 on 2025-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0027_alter_tournamentinstitution_adjudicators_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name may be used for team names or code names', max_length=70, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='tournamentinstitution',
            name='adjudicators_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Adjudicator slots requested'),
        ),
        migrations.AlterField(
            model_name='tournamentinstitution',
            name='teams_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Team slots requested'),
        ),
    ]
