# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0028_auto_20170522_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='efl',
            field=models.BooleanField(default=False, help_text='EFL language status may have its own Break Category or Top Speakers Tab'),
        ),
        migrations.AddField(
            model_name='person',
            name='esl',
            field=models.BooleanField(default=False, help_text='ESL language status may have its own Break Category or Top Speakers Tab'),
        ),
        migrations.AlterField(
            model_name='person',
            name='novice',
            field=models.BooleanField(default=False, help_text='Novice status may be indicated on the tab, and may have its own Break Category or Top Speakers Tab'),
        ),
    ]
