# Generated by Django 5.2.7 on 2025-10-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0029_alter_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicator',
            name='registration_status',
            field=models.CharField(choices=[('U', 'Unconfirmed'), ('C', 'Confirmed')], default='C', help_text="Whether the adjudicator's registration has been confirmed by tournament staff", max_length=1, verbose_name='registration status'),
        ),
        migrations.AddField(
            model_name='team',
            name='registration_status',
            field=models.CharField(choices=[('U', 'Unconfirmed'), ('C', 'Confirmed')], default='C', help_text="Whether the team's registration has been confirmed by tournament staff", max_length=1, verbose_name='registration status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name may be used for team names or code names', max_length=70, null=True, verbose_name='last name'),
        ),
    ]
