# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0031_convert_speaker_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicator',
            name='trainee',
            field=models.BooleanField(default=False, help_text='If checked, this adjudicator will never be auto-allocated a voting position, regardless of their score', verbose_name='always trainee'),
        ),
    ]
