# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:30
from __future__ import unicode_literals

from django.db import migrations


def convert_adjudicator_trainee(apps, schema_editor):
    """Copies Adjudicator.novice to Adjudicator.trainee"""
    Adjudicator = apps.get_model("participants", "Adjudicator")

    for adj in Adjudicator.objects.all():
        adj.trainee = adj.novice
        adj.save()


def unconvert_adjudicator_trainee(apps, schema_editor):
    """Copies Adjudicator.trainee to Adjudicator.novice"""
    Adjudicator = apps.get_model("participants", "Adjudicator")

    for adj in Adjudicator.objects.all():
        adj.novice = adj.trainee
        adj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0032_adjudicator_trainee'),
    ]

    operations = [
        migrations.RunPython(convert_adjudicator_trainee, reverse_code=unconvert_adjudicator_trainee),
    ]
