# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0033_convert_adjudicator_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakercategory',
            name='name',
            field=models.CharField(help_text='Name to be displayed, e.g., "Novice", "ESL"', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='speakercategory',
            name='slug',
            field=models.SlugField(help_text='Slug for URLs, e.g., "novice", "esl"', verbose_name='slug'),
        ),
    ]
