# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0034_auto_20170812_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], help_text='Gender is displayed in the adjudicator allocation interface, and nowhere else', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('N', 'none'), ('S', 'swing'), ('C', 'composite'), ('B', 'bye')], default='N', max_length=1, verbose_name='type'),
        ),
    ]
