# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0036_auto_20170813_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicator',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.Institution', verbose_name='institution'),
        ),
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participants.Institution', verbose_name='institution'),
        ),
    ]
