# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0036_auto_20170813_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail address'),
        ),
    ]
