# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0037_auto_20170813_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='abbreviation',
        ),
    ]
