# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0039_auto_20170923_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='name'),
        ),
    ]
