# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('adjallocation', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateadjudicator',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='debateadjudicator',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.Debate'),
        ),
        migrations.AddField(
            model_name='adjudicatorinstitutionconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorinstitutionconflict',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Institution'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatorconflict',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Team'),
        ),
        migrations.AddField(
            model_name='adjudicatoradjudicatorconflict',
            name='adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_adjudicator', to='participants.Adjudicator'),
        ),
        migrations.AddField(
            model_name='adjudicatoradjudicatorconflict',
            name='conflict_adjudicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_adjudicator', to='participants.Adjudicator', verbose_name='Adjudicator'),
        ),
    ]
