# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0005_auto_20160209_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjudicatoradjudicatorconflict',
            options={'verbose_name': 'adjudicator-adjudicator conflict'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatorconflict',
            options={'verbose_name': 'adjudicator-team conflict'},
        ),
        migrations.AlterModelOptions(
            name='adjudicatorinstitutionconflict',
            options={'verbose_name': 'adjudicator-institution conflict'},
        ),
        migrations.AlterModelOptions(
            name='debateadjudicator',
            options={},
        ),
    ]
