# Generated by Django 2.0.2 on 2018-02-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('options', '0002_move_welcome_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='welcome_msg',
        ),
    ]
