# Generated by Django 2.0.8 on 2018-08-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_convert_current_round_to_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='current_round',
        ),
    ]
