# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20160201_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='adjudicator_status',
        ),
        migrations.RemoveField(
            model_name='round',
            name='venue_status',
        ),
    ]
