# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_auto_20160621_1129'),
        ('motions', '0006_auto_20160621_1129'),
        ('participants', '0014_auto_20160621_1129'),
        ('draw', '0009_auto_20160621_1129'),
        ('tournaments', '0010_auto_20160402_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='division',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='division',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='division',
            name='venue_group',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
