# Generated by Django 4.1.7 on 2024-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_round_draw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
