# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20160621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(help_text='The sub-URL of the tournament, cannot have spaces, e.g. "australs2016"', unique=True, validators=[tournaments.models.validate_tournament_slug]),
        ),
    ]
