# Generated by Django 5.0.4 on 2024-05-04 13:21

import utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakqual', '0006_alter_breakcategory_unique_together_and_more'),
        ('tournaments', '0011_alter_round_starts_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='round',
            index_together=set(),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=utils.models.UniqueConstraint(fields=('tournament', 'seq'), name='tournam_round_tournament__seq_uniq'),
        ),
    ]
