# Generated by Django 4.2.13 on 2024-06-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0012_alter_round_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "Lunch"', max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("C", "Check-in"),
                            ("I", "Briefing"),
                            ("T", "Draw/motion announcement"),
                            ("P", "Preparation time"),
                            ("D", "Debate"),
                            ("J", "Adjudication"),
                            ("R", "Meal/break"),
                            ("B", "Break announcement"),
                            ("A", "Award ceremony"),
                            ("O", "Other"),
                        ],
                        default="O",
                        help_text='What sort of event this is, use "Other" if the type is not available',
                        max_length=1,
                        verbose_name="event type",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="The time the event starts", verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The time at which the event ends, may be empty",
                        null=True,
                        verbose_name="end time",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the event belongs to a specific round, which round",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tournaments.round",
                        verbose_name="round",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="The tournament the event takes place in",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                        verbose_name="tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule event",
                "verbose_name_plural": "schedule events",
                "ordering": ["tournament", "start_time"],
            },
        ),
    ]
