# Generated by Django 5.2.7 on 2025-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='motions_status',
            field=models.CharField(choices=[('N', 'Not released'), ('I', 'Info-slides released'), ('M', 'Motions released')], default='N', help_text='The release status of motions for this round', max_length=1, verbose_name='motions status'),
        ),
        migrations.RunSQL(
            "UPDATE tournaments_round SET motions_status = 'M' WHERE motions_released = 't';",
            "UPDATE tournaments_round SET motions_released = 't' WHERE motions_status = 'M';"
        ),
        migrations.RemoveField(
            model_name='round',
            name='motions_released',
        ),
    ]
