# Generated by Django 4.2.13 on 2024-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0013_scheduleevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("C", "Check-in"),
                    ("I", "Briefing"),
                    ("T", "Draw/motion announcement"),
                    ("P", "Preparation time"),
                    ("D", "Debate"),
                    ("J", "Adjudication"),
                    ("R", "Meal/break"),
                    ("B", "Break announcement"),
                    ("A", "Award ceremony"),
                    ("O", "Other"),
                ],
                default="O",
                help_text='What sort of event this is, use "Other" if the type is not available',
                max_length=1,
                verbose_name="event type",
            ),
        ),
    ]
