# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_delete_old_availability_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.ForeignKey(blank=True, help_text='Must be set for the tournament to start! (Set after rounds are inputted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_', to='tournaments.Round'),
        ),
    ]
