# Generated by Django 5.2.8 on 2026-02-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_round_motions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='draw_status',
            field=models.CharField(choices=[('N', 'None'), ('D', 'Draft'), ('C', 'Confirmed'), ('T', 'Teams released'), ('R', 'Released')], default='N', help_text="The status of this round's draw", max_length=1, verbose_name='draw status'),
        ),
    ]
