# Generated by Django 5.2.12 on 2026-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_round_draw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='schedule_group',
            field=models.PositiveIntegerField(
                default=1,
                # db_default=models.F('seq'), # Django doesn't support this yet
                help_text='Rounds in the same schedule slot (e.g. parallel panels A/B) share this value. Defaults to the sequence number when each slot has only one round.',
                verbose_name='schedule group',
            ),
        ),
        migrations.RunSQL("UPDATE tournaments_round SET schedule_group=seq", migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='round',
            name='schedule_group',
            field=models.PositiveIntegerField(
                null=False,
                blank=False,
                help_text='Rounds in the same schedule slot (e.g. parallel panels A/B) share this value. Defaults to the sequence number when each slot has only one round.',
                verbose_name='schedule group',
            ),
        ),
    ]
