# Generated by Django 5.0.4 on 2026-01-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_round_draw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='undelayable',
            field=models.BooleanField(default=False, help_text='Tick this box if this event cannot be delayed, e.g. a social event with reservations.', verbose_name='Do not delay event'),
        ),
    ]
