# Generated by Django 4.2.13 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0016_round_schedule_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleevent",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional custom title; leave blank to use the event type and round",
                max_length=100,
                verbose_name="title",
            ),
        ),
    ]
