# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20160910_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='The name used in the menu, e.g. "Australs 2016"', max_length=25),
        ),
    ]
