# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_auto_20170422_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(help_text='The full name, e.g. "Australasian Intervarsity Debating Championships 2016"', max_length=100, verbose_name='name'),
        ),
    ]
