# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20170907_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='draw_type',
            field=models.CharField(choices=[('R', 'Random'), ('M', 'Manual'), ('D', 'Round-robin'), ('P', 'Power-paired'), ('E', 'Elimination')], help_text='Which draw method to use', max_length=1, verbose_name='draw type'),
        ),
    ]
