# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 11:16
from __future__ import unicode_literals

from django.db import migrations


def convert_elim_draw_types(apps, schema_editor):
    Round = apps.get_model("tournaments", "Round")
    Round.objects.filter(draw_type='B').update(draw_type='E')
    Round.objects.filter(draw_type='F').update(draw_type='E')


def convert_elim_draw_types_reverse(apps, schema_editor):
    Round = apps.get_model("tournaments", "Round")
    # Not strictly correct, as the first one should be 'B', but old code had
    # checks for this problem, as it was sometimes a user error.
    Round.objects.filter(draw_type='E').update(draw_type='B')


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_auto_20170913_1116'),
    ]

    operations = [
        migrations.RunPython(convert_elim_draw_types, reverse_code=convert_elim_draw_types_reverse),
    ]
