# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_convert_elim_draw_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='emoji',
        ),
    ]
